<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: room/share4.proto

namespace User\Room;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 *楼栋号删除
 *
 * Generated from protobuf message <code>user.room.UserRoomDelReq</code>
 */
class UserRoomDelReq extends \Google\Protobuf\Internal\Message
{
    /**
     *自增id
     *
     * Generated from protobuf field <code>int32 eur_id = 1;</code>
     */
    private $eur_id = 0;

    public function __construct() {
        \GPBMetadata\Room\Share4::initOnce();
        parent::__construct();
    }

    /**
     *自增id
     *
     * Generated from protobuf field <code>int32 eur_id = 1;</code>
     * @return int
     */
    public function getEurId()
    {
        return $this->eur_id;
    }

    /**
     *自增id
     *
     * Generated from protobuf field <code>int32 eur_id = 1;</code>
     * @param int $var
     * @return $this
     */
    public function setEurId($var)
    {
        GPBUtil::checkInt32($var);
        $this->eur_id = $var;

        return $this;
    }

}

