<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: room/share4.proto

namespace User\Room;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 *楼栋号添加
 *
 * Generated from protobuf message <code>user.room.UserRoomAddReq</code>
 */
class UserRoomAddReq extends \Google\Protobuf\Internal\Message
{
    /**
     *用户id
     *
     * Generated from protobuf field <code>int64 user_id = 1;</code>
     */
    private $user_id = 0;
    /**
     *楼栋id
     *
     * Generated from protobuf field <code>int32 build_id = 2;</code>
     */
    private $build_id = 0;
    /**
     *楼栋名称
     *
     * Generated from protobuf field <code>int32 build_name = 3;</code>
     */
    private $build_name = 0;
    /**
     *单元id
     *
     * Generated from protobuf field <code>int32 room_id = 4;</code>
     */
    private $room_id = 0;
    /**
     *单元号名称
     *
     * Generated from protobuf field <code>string unit_name = 5;</code>
     */
    private $unit_name = '';
    /**
     *是否自有
     *
     * Generated from protobuf field <code>.user.Enumerate owner = 6;</code>
     */
    private $owner = 0;

    public function __construct() {
        \GPBMetadata\Room\Share4::initOnce();
        parent::__construct();
    }

    /**
     *用户id
     *
     * Generated from protobuf field <code>int64 user_id = 1;</code>
     * @return int|string
     */
    public function getUserId()
    {
        return $this->user_id;
    }

    /**
     *用户id
     *
     * Generated from protobuf field <code>int64 user_id = 1;</code>
     * @param int|string $var
     * @return $this
     */
    public function setUserId($var)
    {
        GPBUtil::checkInt64($var);
        $this->user_id = $var;

        return $this;
    }

    /**
     *楼栋id
     *
     * Generated from protobuf field <code>int32 build_id = 2;</code>
     * @return int
     */
    public function getBuildId()
    {
        return $this->build_id;
    }

    /**
     *楼栋id
     *
     * Generated from protobuf field <code>int32 build_id = 2;</code>
     * @param int $var
     * @return $this
     */
    public function setBuildId($var)
    {
        GPBUtil::checkInt32($var);
        $this->build_id = $var;

        return $this;
    }

    /**
     *楼栋名称
     *
     * Generated from protobuf field <code>int32 build_name = 3;</code>
     * @return int
     */
    public function getBuildName()
    {
        return $this->build_name;
    }

    /**
     *楼栋名称
     *
     * Generated from protobuf field <code>int32 build_name = 3;</code>
     * @param int $var
     * @return $this
     */
    public function setBuildName($var)
    {
        GPBUtil::checkInt32($var);
        $this->build_name = $var;

        return $this;
    }

    /**
     *单元id
     *
     * Generated from protobuf field <code>int32 room_id = 4;</code>
     * @return int
     */
    public function getRoomId()
    {
        return $this->room_id;
    }

    /**
     *单元id
     *
     * Generated from protobuf field <code>int32 room_id = 4;</code>
     * @param int $var
     * @return $this
     */
    public function setRoomId($var)
    {
        GPBUtil::checkInt32($var);
        $this->room_id = $var;

        return $this;
    }

    /**
     *单元号名称
     *
     * Generated from protobuf field <code>string unit_name = 5;</code>
     * @return string
     */
    public function getUnitName()
    {
        return $this->unit_name;
    }

    /**
     *单元号名称
     *
     * Generated from protobuf field <code>string unit_name = 5;</code>
     * @param string $var
     * @return $this
     */
    public function setUnitName($var)
    {
        GPBUtil::checkString($var, True);
        $this->unit_name = $var;

        return $this;
    }

    /**
     *是否自有
     *
     * Generated from protobuf field <code>.user.Enumerate owner = 6;</code>
     * @return int
     */
    public function getOwner()
    {
        return $this->owner;
    }

    /**
     *是否自有
     *
     * Generated from protobuf field <code>.user.Enumerate owner = 6;</code>
     * @param int $var
     * @return $this
     */
    public function setOwner($var)
    {
        GPBUtil::checkEnum($var, \User\Enumerate::class);
        $this->owner = $var;

        return $this;
    }

}

