<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: station/share4.proto

namespace User\Station;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 *后台车场更新
 *
 * Generated from protobuf message <code>user.station.MemberStationUpdateReq</code>
 */
class MemberStationUpdateReq extends \Google\Protobuf\Internal\Message
{
    /**
     *后台id
     *
     * Generated from protobuf field <code>int32 member_id = 1;</code>
     */
    private $member_id = 0;
    /**
     *车场id集合
     *
     * Generated from protobuf field <code>string station_ids = 2;</code>
     */
    private $station_ids = '';

    public function __construct() {
        \GPBMetadata\Station\Share4::initOnce();
        parent::__construct();
    }

    /**
     *后台id
     *
     * Generated from protobuf field <code>int32 member_id = 1;</code>
     * @return int
     */
    public function getMemberId()
    {
        return $this->member_id;
    }

    /**
     *后台id
     *
     * Generated from protobuf field <code>int32 member_id = 1;</code>
     * @param int $var
     * @return $this
     */
    public function setMemberId($var)
    {
        GPBUtil::checkInt32($var);
        $this->member_id = $var;

        return $this;
    }

    /**
     *车场id集合
     *
     * Generated from protobuf field <code>string station_ids = 2;</code>
     * @return string
     */
    public function getStationIds()
    {
        return $this->station_ids;
    }

    /**
     *车场id集合
     *
     * Generated from protobuf field <code>string station_ids = 2;</code>
     * @param string $var
     * @return $this
     */
    public function setStationIds($var)
    {
        GPBUtil::checkString($var, True);
        $this->station_ids = $var;

        return $this;
    }

}

