<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: weuser/share4.proto

namespace User\Weuser;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 *微信拓展信息展示
 *
 * Generated from protobuf message <code>user.weuser.WeuserShowReq</code>
 */
class WeuserShowReq extends \Google\Protobuf\Internal\Message
{
    /**
     *客户端id
     *
     * Generated from protobuf field <code>int32 client_id = 1;</code>
     */
    private $client_id = 0;
    /**
     *自增id
     *
     * Generated from protobuf field <code>int32 weuser_id = 2;</code>
     */
    private $weuser_id = 0;

    public function __construct() {
        \GPBMetadata\Weuser\Share4::initOnce();
        parent::__construct();
    }

    /**
     *客户端id
     *
     * Generated from protobuf field <code>int32 client_id = 1;</code>
     * @return int
     */
    public function getClientId()
    {
        return $this->client_id;
    }

    /**
     *客户端id
     *
     * Generated from protobuf field <code>int32 client_id = 1;</code>
     * @param int $var
     * @return $this
     */
    public function setClientId($var)
    {
        GPBUtil::checkInt32($var);
        $this->client_id = $var;

        return $this;
    }

    /**
     *自增id
     *
     * Generated from protobuf field <code>int32 weuser_id = 2;</code>
     * @return int
     */
    public function getWeuserId()
    {
        return $this->weuser_id;
    }

    /**
     *自增id
     *
     * Generated from protobuf field <code>int32 weuser_id = 2;</code>
     * @param int $var
     * @return $this
     */
    public function setWeuserId($var)
    {
        GPBUtil::checkInt32($var);
        $this->weuser_id = $var;

        return $this;
    }

}

