<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: user/share4.proto

namespace User\User;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 *新增客户端数据
 *
 * Generated from protobuf message <code>user.user.ClientNumReq</code>
 */
class ClientNumReq extends \Google\Protobuf\Internal\Message
{
    /**
     *ymd:获取每天得增加量,ym:获取每月得增加量，y,"获取每年得增加量"
     *
     * Generated from protobuf field <code>string type = 1;</code>
     */
    private $type = '';
    /**
     *日期，ymd：2019-12-26 ym：2019-12或y:2019格式，
     *
     * Generated from protobuf field <code>string date = 2;</code>
     */
    private $date = '';

    public function __construct() {
        \GPBMetadata\User\Share4::initOnce();
        parent::__construct();
    }

    /**
     *ymd:获取每天得增加量,ym:获取每月得增加量，y,"获取每年得增加量"
     *
     * Generated from protobuf field <code>string type = 1;</code>
     * @return string
     */
    public function getType()
    {
        return $this->type;
    }

    /**
     *ymd:获取每天得增加量,ym:获取每月得增加量，y,"获取每年得增加量"
     *
     * Generated from protobuf field <code>string type = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setType($var)
    {
        GPBUtil::checkString($var, True);
        $this->type = $var;

        return $this;
    }

    /**
     *日期，ymd：2019-12-26 ym：2019-12或y:2019格式，
     *
     * Generated from protobuf field <code>string date = 2;</code>
     * @return string
     */
    public function getDate()
    {
        return $this->date;
    }

    /**
     *日期，ymd：2019-12-26 ym：2019-12或y:2019格式，
     *
     * Generated from protobuf field <code>string date = 2;</code>
     * @param string $var
     * @return $this
     */
    public function setDate($var)
    {
        GPBUtil::checkString($var, True);
        $this->date = $var;

        return $this;
    }

}

