<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: user/share4.proto

namespace User\User;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 *展示client列表
 *
 * Generated from protobuf message <code>user.user.ShowClientListsReq</code>
 */
class ShowClientListsReq extends \Google\Protobuf\Internal\Message
{
    /**
     *用户id
     *
     * Generated from protobuf field <code>int64 user_id = 1;</code>
     */
    private $user_id = 0;
    /**
     *用户id集合
     *
     * Generated from protobuf field <code>repeated int64 user_ids = 2;</code>
     */
    private $user_ids;
    /**
     *应用id
     *
     * Generated from protobuf field <code>string app_id = 3;</code>
     */
    private $app_id = '';
    /**
     *授权id
     *
     * Generated from protobuf field <code>string openid = 4;</code>
     */
    private $openid = '';
    /**
     *客户端id
     *
     * Generated from protobuf field <code>int64 client_id = 5;</code>
     */
    private $client_id = 0;
    /**
     *客户端id集合
     *
     * Generated from protobuf field <code>repeated int64 client_ids = 6;</code>
     */
    private $client_ids;

    public function __construct() {
        \GPBMetadata\User\Share4::initOnce();
        parent::__construct();
    }

    /**
     *用户id
     *
     * Generated from protobuf field <code>int64 user_id = 1;</code>
     * @return int|string
     */
    public function getUserId()
    {
        return $this->user_id;
    }

    /**
     *用户id
     *
     * Generated from protobuf field <code>int64 user_id = 1;</code>
     * @param int|string $var
     * @return $this
     */
    public function setUserId($var)
    {
        GPBUtil::checkInt64($var);
        $this->user_id = $var;

        return $this;
    }

    /**
     *用户id集合
     *
     * Generated from protobuf field <code>repeated int64 user_ids = 2;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getUserIds()
    {
        return $this->user_ids;
    }

    /**
     *用户id集合
     *
     * Generated from protobuf field <code>repeated int64 user_ids = 2;</code>
     * @param int[]|string[]|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setUserIds($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::INT64);
        $this->user_ids = $arr;

        return $this;
    }

    /**
     *应用id
     *
     * Generated from protobuf field <code>string app_id = 3;</code>
     * @return string
     */
    public function getAppId()
    {
        return $this->app_id;
    }

    /**
     *应用id
     *
     * Generated from protobuf field <code>string app_id = 3;</code>
     * @param string $var
     * @return $this
     */
    public function setAppId($var)
    {
        GPBUtil::checkString($var, True);
        $this->app_id = $var;

        return $this;
    }

    /**
     *授权id
     *
     * Generated from protobuf field <code>string openid = 4;</code>
     * @return string
     */
    public function getOpenid()
    {
        return $this->openid;
    }

    /**
     *授权id
     *
     * Generated from protobuf field <code>string openid = 4;</code>
     * @param string $var
     * @return $this
     */
    public function setOpenid($var)
    {
        GPBUtil::checkString($var, True);
        $this->openid = $var;

        return $this;
    }

    /**
     *客户端id
     *
     * Generated from protobuf field <code>int64 client_id = 5;</code>
     * @return int|string
     */
    public function getClientId()
    {
        return $this->client_id;
    }

    /**
     *客户端id
     *
     * Generated from protobuf field <code>int64 client_id = 5;</code>
     * @param int|string $var
     * @return $this
     */
    public function setClientId($var)
    {
        GPBUtil::checkInt64($var);
        $this->client_id = $var;

        return $this;
    }

    /**
     *客户端id集合
     *
     * Generated from protobuf field <code>repeated int64 client_ids = 6;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getClientIds()
    {
        return $this->client_ids;
    }

    /**
     *客户端id集合
     *
     * Generated from protobuf field <code>repeated int64 client_ids = 6;</code>
     * @param int[]|string[]|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setClientIds($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::INT64);
        $this->client_ids = $arr;

        return $this;
    }

}

