<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: user/share4.proto

namespace User\User;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 *展示用户信息返回参数
 *
 * Generated from protobuf message <code>user.user.ShowUsersRes</code>
 */
class ShowUsersRes extends \Google\Protobuf\Internal\Message
{
    /**
     *返回编码
     *
     * Generated from protobuf field <code>int32 code = 1;</code>
     */
    private $code = 0;
    /**
     *内容
     *
     * Generated from protobuf field <code>.user.ShowUsersData content = 2;</code>
     */
    private $content = null;
    /**
     *提示信息
     *
     * Generated from protobuf field <code>string message = 3;</code>
     */
    private $message = '';

    public function __construct() {
        \GPBMetadata\User\Share4::initOnce();
        parent::__construct();
    }

    /**
     *返回编码
     *
     * Generated from protobuf field <code>int32 code = 1;</code>
     * @return int
     */
    public function getCode()
    {
        return $this->code;
    }

    /**
     *返回编码
     *
     * Generated from protobuf field <code>int32 code = 1;</code>
     * @param int $var
     * @return $this
     */
    public function setCode($var)
    {
        GPBUtil::checkInt32($var);
        $this->code = $var;

        return $this;
    }

    /**
     *内容
     *
     * Generated from protobuf field <code>.user.ShowUsersData content = 2;</code>
     * @return \User\ShowUsersData
     */
    public function getContent()
    {
        return $this->content;
    }

    /**
     *内容
     *
     * Generated from protobuf field <code>.user.ShowUsersData content = 2;</code>
     * @param \User\ShowUsersData $var
     * @return $this
     */
    public function setContent($var)
    {
        GPBUtil::checkMessage($var, \User\ShowUsersData::class);
        $this->content = $var;

        return $this;
    }

    /**
     *提示信息
     *
     * Generated from protobuf field <code>string message = 3;</code>
     * @return string
     */
    public function getMessage()
    {
        return $this->message;
    }

    /**
     *提示信息
     *
     * Generated from protobuf field <code>string message = 3;</code>
     * @param string $var
     * @return $this
     */
    public function setMessage($var)
    {
        GPBUtil::checkString($var, True);
        $this->message = $var;

        return $this;
    }

}

