<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: user/share4.proto

namespace User\User;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 *展示客户端响应数据
 *
 * Generated from protobuf message <code>user.user.ShowClientRes</code>
 */
class ShowClientRes extends \Google\Protobuf\Internal\Message
{
    /**
     *返回码
     *
     * Generated from protobuf field <code>int64 code = 1;</code>
     */
    private $code = 0;
    /**
     *返回数据
     *
     * Generated from protobuf field <code>.user.ShowClientData content = 2;</code>
     */
    private $content = null;
    /**
     *提示信息
     *
     * Generated from protobuf field <code>string message = 3;</code>
     */
    private $message = '';

    public function __construct() {
        \GPBMetadata\User\Share4::initOnce();
        parent::__construct();
    }

    /**
     *返回码
     *
     * Generated from protobuf field <code>int64 code = 1;</code>
     * @return int|string
     */
    public function getCode()
    {
        return $this->code;
    }

    /**
     *返回码
     *
     * Generated from protobuf field <code>int64 code = 1;</code>
     * @param int|string $var
     * @return $this
     */
    public function setCode($var)
    {
        GPBUtil::checkInt64($var);
        $this->code = $var;

        return $this;
    }

    /**
     *返回数据
     *
     * Generated from protobuf field <code>.user.ShowClientData content = 2;</code>
     * @return \User\ShowClientData
     */
    public function getContent()
    {
        return $this->content;
    }

    /**
     *返回数据
     *
     * Generated from protobuf field <code>.user.ShowClientData content = 2;</code>
     * @param \User\ShowClientData $var
     * @return $this
     */
    public function setContent($var)
    {
        GPBUtil::checkMessage($var, \User\ShowClientData::class);
        $this->content = $var;

        return $this;
    }

    /**
     *提示信息
     *
     * Generated from protobuf field <code>string message = 3;</code>
     * @return string
     */
    public function getMessage()
    {
        return $this->message;
    }

    /**
     *提示信息
     *
     * Generated from protobuf field <code>string message = 3;</code>
     * @param string $var
     * @return $this
     */
    public function setMessage($var)
    {
        GPBUtil::checkString($var, True);
        $this->message = $var;

        return $this;
    }

}

