<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: user/share4.proto

namespace User\User;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 *用户展示返回
 *
 * Generated from protobuf message <code>user.user.UsersShowRes</code>
 */
class UsersShowRes extends \Google\Protobuf\Internal\Message
{
    /**
     *返回码
     *
     * Generated from protobuf field <code>int32 code = 1;</code>
     */
    private $code = 0;
    /**
     *返回内容
     *
     * Generated from protobuf field <code>.user.UsersShowData content = 2;</code>
     */
    private $content = null;
    /**
     *返回信息
     *
     * Generated from protobuf field <code>string message = 3;</code>
     */
    private $message = '';

    public function __construct() {
        \GPBMetadata\User\Share4::initOnce();
        parent::__construct();
    }

    /**
     *返回码
     *
     * Generated from protobuf field <code>int32 code = 1;</code>
     * @return int
     */
    public function getCode()
    {
        return $this->code;
    }

    /**
     *返回码
     *
     * Generated from protobuf field <code>int32 code = 1;</code>
     * @param int $var
     * @return $this
     */
    public function setCode($var)
    {
        GPBUtil::checkInt32($var);
        $this->code = $var;

        return $this;
    }

    /**
     *返回内容
     *
     * Generated from protobuf field <code>.user.UsersShowData content = 2;</code>
     * @return \User\UsersShowData
     */
    public function getContent()
    {
        return $this->content;
    }

    /**
     *返回内容
     *
     * Generated from protobuf field <code>.user.UsersShowData content = 2;</code>
     * @param \User\UsersShowData $var
     * @return $this
     */
    public function setContent($var)
    {
        GPBUtil::checkMessage($var, \User\UsersShowData::class);
        $this->content = $var;

        return $this;
    }

    /**
     *返回信息
     *
     * Generated from protobuf field <code>string message = 3;</code>
     * @return string
     */
    public function getMessage()
    {
        return $this->message;
    }

    /**
     *返回信息
     *
     * Generated from protobuf field <code>string message = 3;</code>
     * @param string $var
     * @return $this
     */
    public function setMessage($var)
    {
        GPBUtil::checkString($var, True);
        $this->message = $var;

        return $this;
    }

}

