<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: user/share4.proto

namespace User\User;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 *nats用户更新
 *
 * Generated from protobuf message <code>user.user.UserUpdatelocalReq</code>
 */
class UserUpdatelocalReq extends \Google\Protobuf\Internal\Message
{
    /**
     *性别
     *
     * Generated from protobuf field <code>string sex = 2;</code>
     */
    private $sex = '';
    /**
     *全名
     *
     * Generated from protobuf field <code>string fullname = 3;</code>
     */
    private $fullname = '';
    /**
     *手机号
     *
     * Generated from protobuf field <code>string mobile = 6;</code>
     */
    private $mobile = '';

    public function __construct() {
        \GPBMetadata\User\Share4::initOnce();
        parent::__construct();
    }

    /**
     *性别
     *
     * Generated from protobuf field <code>string sex = 2;</code>
     * @return string
     */
    public function getSex()
    {
        return $this->sex;
    }

    /**
     *性别
     *
     * Generated from protobuf field <code>string sex = 2;</code>
     * @param string $var
     * @return $this
     */
    public function setSex($var)
    {
        GPBUtil::checkString($var, True);
        $this->sex = $var;

        return $this;
    }

    /**
     *全名
     *
     * Generated from protobuf field <code>string fullname = 3;</code>
     * @return string
     */
    public function getFullname()
    {
        return $this->fullname;
    }

    /**
     *全名
     *
     * Generated from protobuf field <code>string fullname = 3;</code>
     * @param string $var
     * @return $this
     */
    public function setFullname($var)
    {
        GPBUtil::checkString($var, True);
        $this->fullname = $var;

        return $this;
    }

    /**
     *手机号
     *
     * Generated from protobuf field <code>string mobile = 6;</code>
     * @return string
     */
    public function getMobile()
    {
        return $this->mobile;
    }

    /**
     *手机号
     *
     * Generated from protobuf field <code>string mobile = 6;</code>
     * @param string $var
     * @return $this
     */
    public function setMobile($var)
    {
        GPBUtil::checkString($var, True);
        $this->mobile = $var;

        return $this;
    }

}

