<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: user/share4.proto

namespace User\User;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 *更新用户信息
 *
 * Generated from protobuf message <code>user.user.UserUpdateReq</code>
 */
class UserUpdateReq extends \Google\Protobuf\Internal\Message
{
    /**
     *用户id
     *
     * Generated from protobuf field <code>int64 user_id = 1;</code>
     */
    private $user_id = 0;
    /**
     *性别
     *
     * Generated from protobuf field <code>string sex = 2;</code>
     */
    private $sex = '';
    /**
     *全名
     *
     * Generated from protobuf field <code>string fullname = 3;</code>
     */
    private $fullname = '';
    /**
     *昵称
     *
     * Generated from protobuf field <code>string nickname = 4;</code>
     */
    private $nickname = '';
    /**
     *用户名
     *
     * Generated from protobuf field <code>string username = 5;</code>
     */
    private $username = '';
    /**
     *手机号
     *
     * Generated from protobuf field <code>string mobile = 6;</code>
     */
    private $mobile = '';
    /**
     *邮箱
     *
     * Generated from protobuf field <code>string email = 7;</code>
     */
    private $email = '';
    /**
     *头像
     *
     * Generated from protobuf field <code>string head_img = 8;</code>
     */
    private $head_img = '';
    /**
     *状态
     *
     * Generated from protobuf field <code>string status = 9;</code>
     */
    private $status = '';
    /**
     *是否验证
     *
     * Generated from protobuf field <code>string verify = 10;</code>
     */
    private $verify = '';
    /**
     *是否自动锁定
     *
     * Generated from protobuf field <code>string autolock = 11;</code>
     */
    private $autolock = '';

    public function __construct() {
        \GPBMetadata\User\Share4::initOnce();
        parent::__construct();
    }

    /**
     *用户id
     *
     * Generated from protobuf field <code>int64 user_id = 1;</code>
     * @return int|string
     */
    public function getUserId()
    {
        return $this->user_id;
    }

    /**
     *用户id
     *
     * Generated from protobuf field <code>int64 user_id = 1;</code>
     * @param int|string $var
     * @return $this
     */
    public function setUserId($var)
    {
        GPBUtil::checkInt64($var);
        $this->user_id = $var;

        return $this;
    }

    /**
     *性别
     *
     * Generated from protobuf field <code>string sex = 2;</code>
     * @return string
     */
    public function getSex()
    {
        return $this->sex;
    }

    /**
     *性别
     *
     * Generated from protobuf field <code>string sex = 2;</code>
     * @param string $var
     * @return $this
     */
    public function setSex($var)
    {
        GPBUtil::checkString($var, True);
        $this->sex = $var;

        return $this;
    }

    /**
     *全名
     *
     * Generated from protobuf field <code>string fullname = 3;</code>
     * @return string
     */
    public function getFullname()
    {
        return $this->fullname;
    }

    /**
     *全名
     *
     * Generated from protobuf field <code>string fullname = 3;</code>
     * @param string $var
     * @return $this
     */
    public function setFullname($var)
    {
        GPBUtil::checkString($var, True);
        $this->fullname = $var;

        return $this;
    }

    /**
     *昵称
     *
     * Generated from protobuf field <code>string nickname = 4;</code>
     * @return string
     */
    public function getNickname()
    {
        return $this->nickname;
    }

    /**
     *昵称
     *
     * Generated from protobuf field <code>string nickname = 4;</code>
     * @param string $var
     * @return $this
     */
    public function setNickname($var)
    {
        GPBUtil::checkString($var, True);
        $this->nickname = $var;

        return $this;
    }

    /**
     *用户名
     *
     * Generated from protobuf field <code>string username = 5;</code>
     * @return string
     */
    public function getUsername()
    {
        return $this->username;
    }

    /**
     *用户名
     *
     * Generated from protobuf field <code>string username = 5;</code>
     * @param string $var
     * @return $this
     */
    public function setUsername($var)
    {
        GPBUtil::checkString($var, True);
        $this->username = $var;

        return $this;
    }

    /**
     *手机号
     *
     * Generated from protobuf field <code>string mobile = 6;</code>
     * @return string
     */
    public function getMobile()
    {
        return $this->mobile;
    }

    /**
     *手机号
     *
     * Generated from protobuf field <code>string mobile = 6;</code>
     * @param string $var
     * @return $this
     */
    public function setMobile($var)
    {
        GPBUtil::checkString($var, True);
        $this->mobile = $var;

        return $this;
    }

    /**
     *邮箱
     *
     * Generated from protobuf field <code>string email = 7;</code>
     * @return string
     */
    public function getEmail()
    {
        return $this->email;
    }

    /**
     *邮箱
     *
     * Generated from protobuf field <code>string email = 7;</code>
     * @param string $var
     * @return $this
     */
    public function setEmail($var)
    {
        GPBUtil::checkString($var, True);
        $this->email = $var;

        return $this;
    }

    /**
     *头像
     *
     * Generated from protobuf field <code>string head_img = 8;</code>
     * @return string
     */
    public function getHeadImg()
    {
        return $this->head_img;
    }

    /**
     *头像
     *
     * Generated from protobuf field <code>string head_img = 8;</code>
     * @param string $var
     * @return $this
     */
    public function setHeadImg($var)
    {
        GPBUtil::checkString($var, True);
        $this->head_img = $var;

        return $this;
    }

    /**
     *状态
     *
     * Generated from protobuf field <code>string status = 9;</code>
     * @return string
     */
    public function getStatus()
    {
        return $this->status;
    }

    /**
     *状态
     *
     * Generated from protobuf field <code>string status = 9;</code>
     * @param string $var
     * @return $this
     */
    public function setStatus($var)
    {
        GPBUtil::checkString($var, True);
        $this->status = $var;

        return $this;
    }

    /**
     *是否验证
     *
     * Generated from protobuf field <code>string verify = 10;</code>
     * @return string
     */
    public function getVerify()
    {
        return $this->verify;
    }

    /**
     *是否验证
     *
     * Generated from protobuf field <code>string verify = 10;</code>
     * @param string $var
     * @return $this
     */
    public function setVerify($var)
    {
        GPBUtil::checkString($var, True);
        $this->verify = $var;

        return $this;
    }

    /**
     *是否自动锁定
     *
     * Generated from protobuf field <code>string autolock = 11;</code>
     * @return string
     */
    public function getAutolock()
    {
        return $this->autolock;
    }

    /**
     *是否自动锁定
     *
     * Generated from protobuf field <code>string autolock = 11;</code>
     * @param string $var
     * @return $this
     */
    public function setAutolock($var)
    {
        GPBUtil::checkString($var, True);
        $this->autolock = $var;

        return $this;
    }

}

