<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: user/share4.proto

namespace User\User;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 *nats用户添加
 *
 * Generated from protobuf message <code>user.user.UserAddlocalReq</code>
 */
class UserAddlocalReq extends \Google\Protobuf\Internal\Message
{
    /**
     *性别
     *
     * Generated from protobuf field <code>string sex = 1;</code>
     */
    private $sex = '';
    /**
     *全名
     *
     * Generated from protobuf field <code>string fullname = 2;</code>
     */
    private $fullname = '';
    /**
     *手机号
     *
     * Generated from protobuf field <code>string mobile = 3;</code>
     */
    private $mobile = '';
    /**
     *用户状态
     *
     * Generated from protobuf field <code>.user.Enumerate status = 4;</code>
     */
    private $status = 0;
    /**
     *是否锁定
     *
     * Generated from protobuf field <code>.user.Enumerate autolock = 5;</code>
     */
    private $autolock = 0;
    /**
     *是否验证
     *
     * Generated from protobuf field <code>.user.Enumerate verify = 6;</code>
     */
    private $verify = 0;

    public function __construct() {
        \GPBMetadata\User\Share4::initOnce();
        parent::__construct();
    }

    /**
     *性别
     *
     * Generated from protobuf field <code>string sex = 1;</code>
     * @return string
     */
    public function getSex()
    {
        return $this->sex;
    }

    /**
     *性别
     *
     * Generated from protobuf field <code>string sex = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setSex($var)
    {
        GPBUtil::checkString($var, True);
        $this->sex = $var;

        return $this;
    }

    /**
     *全名
     *
     * Generated from protobuf field <code>string fullname = 2;</code>
     * @return string
     */
    public function getFullname()
    {
        return $this->fullname;
    }

    /**
     *全名
     *
     * Generated from protobuf field <code>string fullname = 2;</code>
     * @param string $var
     * @return $this
     */
    public function setFullname($var)
    {
        GPBUtil::checkString($var, True);
        $this->fullname = $var;

        return $this;
    }

    /**
     *手机号
     *
     * Generated from protobuf field <code>string mobile = 3;</code>
     * @return string
     */
    public function getMobile()
    {
        return $this->mobile;
    }

    /**
     *手机号
     *
     * Generated from protobuf field <code>string mobile = 3;</code>
     * @param string $var
     * @return $this
     */
    public function setMobile($var)
    {
        GPBUtil::checkString($var, True);
        $this->mobile = $var;

        return $this;
    }

    /**
     *用户状态
     *
     * Generated from protobuf field <code>.user.Enumerate status = 4;</code>
     * @return int
     */
    public function getStatus()
    {
        return $this->status;
    }

    /**
     *用户状态
     *
     * Generated from protobuf field <code>.user.Enumerate status = 4;</code>
     * @param int $var
     * @return $this
     */
    public function setStatus($var)
    {
        GPBUtil::checkEnum($var, \User\Enumerate::class);
        $this->status = $var;

        return $this;
    }

    /**
     *是否锁定
     *
     * Generated from protobuf field <code>.user.Enumerate autolock = 5;</code>
     * @return int
     */
    public function getAutolock()
    {
        return $this->autolock;
    }

    /**
     *是否锁定
     *
     * Generated from protobuf field <code>.user.Enumerate autolock = 5;</code>
     * @param int $var
     * @return $this
     */
    public function setAutolock($var)
    {
        GPBUtil::checkEnum($var, \User\Enumerate::class);
        $this->autolock = $var;

        return $this;
    }

    /**
     *是否验证
     *
     * Generated from protobuf field <code>.user.Enumerate verify = 6;</code>
     * @return int
     */
    public function getVerify()
    {
        return $this->verify;
    }

    /**
     *是否验证
     *
     * Generated from protobuf field <code>.user.Enumerate verify = 6;</code>
     * @param int $var
     * @return $this
     */
    public function setVerify($var)
    {
        GPBUtil::checkEnum($var, \User\Enumerate::class);
        $this->verify = $var;

        return $this;
    }

}

