<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: authmidware/share4.proto

namespace User\Authmidware;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 *鉴权设置路由缓存
 *
 * Generated from protobuf message <code>user.authmidware.ApiauthSetroutecacheReq</code>
 */
class ApiauthSetroutecacheReq extends \Google\Protobuf\Internal\Message
{
    /**
     *微服务路由列表
     *
     * Generated from protobuf field <code>repeated .user.ApiauthSetroutecacheData routes = 1;</code>
     */
    private $routes;

    public function __construct() {
        \GPBMetadata\Authmidware\Share4::initOnce();
        parent::__construct();
    }

    /**
     *微服务路由列表
     *
     * Generated from protobuf field <code>repeated .user.ApiauthSetroutecacheData routes = 1;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getRoutes()
    {
        return $this->routes;
    }

    /**
     *微服务路由列表
     *
     * Generated from protobuf field <code>repeated .user.ApiauthSetroutecacheData routes = 1;</code>
     * @param \User\ApiauthSetroutecacheData[]|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setRoutes($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \User\ApiauthSetroutecacheData::class);
        $this->routes = $arr;

        return $this;
    }

}

