<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: authmidware/share4.proto

namespace User\Authmidware;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 *鉴权设置路由权限
 *
 * Generated from protobuf message <code>user.authmidware.ApiauthSetuserrouteReq</code>
 */
class ApiauthSetuserrouteReq extends \Google\Protobuf\Internal\Message
{
    /**
     *用户accesstoken
     *
     * Generated from protobuf field <code>string access_token = 1;</code>
     */
    private $access_token = '';
    /**
     *路由ids
     *
     * Generated from protobuf field <code>string route_ids = 2;</code>
     */
    private $route_ids = '';

    public function __construct() {
        \GPBMetadata\Authmidware\Share4::initOnce();
        parent::__construct();
    }

    /**
     *用户accesstoken
     *
     * Generated from protobuf field <code>string access_token = 1;</code>
     * @return string
     */
    public function getAccessToken()
    {
        return $this->access_token;
    }

    /**
     *用户accesstoken
     *
     * Generated from protobuf field <code>string access_token = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setAccessToken($var)
    {
        GPBUtil::checkString($var, True);
        $this->access_token = $var;

        return $this;
    }

    /**
     *路由ids
     *
     * Generated from protobuf field <code>string route_ids = 2;</code>
     * @return string
     */
    public function getRouteIds()
    {
        return $this->route_ids;
    }

    /**
     *路由ids
     *
     * Generated from protobuf field <code>string route_ids = 2;</code>
     * @param string $var
     * @return $this
     */
    public function setRouteIds($var)
    {
        GPBUtil::checkString($var, True);
        $this->route_ids = $var;

        return $this;
    }

}

