<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: authmidware/share4.proto

namespace User\Authmidware;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 *获取accesstoken
 *
 * Generated from protobuf message <code>user.authmidware.AppauthGetAccessTokenReq</code>
 */
class AppauthGetAccessTokenReq extends \Google\Protobuf\Internal\Message
{
    /**
     *应用id
     *
     * Generated from protobuf field <code>string et_app_id = 1;</code>
     */
    private $et_app_id = '';
    /**
     *签名
     *
     * Generated from protobuf field <code>string sign = 2;</code>
     */
    private $sign = '';

    public function __construct() {
        \GPBMetadata\Authmidware\Share4::initOnce();
        parent::__construct();
    }

    /**
     *应用id
     *
     * Generated from protobuf field <code>string et_app_id = 1;</code>
     * @return string
     */
    public function getEtAppId()
    {
        return $this->et_app_id;
    }

    /**
     *应用id
     *
     * Generated from protobuf field <code>string et_app_id = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setEtAppId($var)
    {
        GPBUtil::checkString($var, True);
        $this->et_app_id = $var;

        return $this;
    }

    /**
     *签名
     *
     * Generated from protobuf field <code>string sign = 2;</code>
     * @return string
     */
    public function getSign()
    {
        return $this->sign;
    }

    /**
     *签名
     *
     * Generated from protobuf field <code>string sign = 2;</code>
     * @param string $var
     * @return $this
     */
    public function setSign($var)
    {
        GPBUtil::checkString($var, True);
        $this->sign = $var;

        return $this;
    }

}

