<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: merchant/share4.proto

namespace User\Merchant;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 *商户删除
 *
 * Generated from protobuf message <code>user.merchant.McDelReq</code>
 */
class McDelReq extends \Google\Protobuf\Internal\Message
{
    /**
     *商户id
     *
     * Generated from protobuf field <code>int32 merchant_id = 1;</code>
     */
    private $merchant_id = 0;

    public function __construct() {
        \GPBMetadata\Merchant\Share4::initOnce();
        parent::__construct();
    }

    /**
     *商户id
     *
     * Generated from protobuf field <code>int32 merchant_id = 1;</code>
     * @return int
     */
    public function getMerchantId()
    {
        return $this->merchant_id;
    }

    /**
     *商户id
     *
     * Generated from protobuf field <code>int32 merchant_id = 1;</code>
     * @param int $var
     * @return $this
     */
    public function setMerchantId($var)
    {
        GPBUtil::checkInt32($var);
        $this->merchant_id = $var;

        return $this;
    }

}

