<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: merchant/share4.proto

namespace User\Merchant;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 *获取商户列表
 *
 * Generated from protobuf message <code>user.merchant.McGetlistReq</code>
 */
class McGetlistReq extends \Google\Protobuf\Internal\Message
{
    /**
     *页码
     *
     * Generated from protobuf field <code>int32 page = 1;</code>
     */
    private $page = 0;
    /**
     *页数
     *
     * Generated from protobuf field <code>int32 pagesize = 2;</code>
     */
    private $pagesize = 0;
    /**
     *商户名称
     *
     * Generated from protobuf field <code>string mc_name = 3;</code>
     */
    private $mc_name = '';
    /**
     *车站
     *
     * Generated from protobuf field <code>int32 station_id = 4;</code>
     */
    private $station_id = 0;
    /**
     *地址
     *
     * Generated from protobuf field <code>string address = 5;</code>
     */
    private $address = '';
    /**
     *商户id
     *
     * Generated from protobuf field <code>int32 merchant_id = 6;</code>
     */
    private $merchant_id = 0;

    public function __construct() {
        \GPBMetadata\Merchant\Share4::initOnce();
        parent::__construct();
    }

    /**
     *页码
     *
     * Generated from protobuf field <code>int32 page = 1;</code>
     * @return int
     */
    public function getPage()
    {
        return $this->page;
    }

    /**
     *页码
     *
     * Generated from protobuf field <code>int32 page = 1;</code>
     * @param int $var
     * @return $this
     */
    public function setPage($var)
    {
        GPBUtil::checkInt32($var);
        $this->page = $var;

        return $this;
    }

    /**
     *页数
     *
     * Generated from protobuf field <code>int32 pagesize = 2;</code>
     * @return int
     */
    public function getPagesize()
    {
        return $this->pagesize;
    }

    /**
     *页数
     *
     * Generated from protobuf field <code>int32 pagesize = 2;</code>
     * @param int $var
     * @return $this
     */
    public function setPagesize($var)
    {
        GPBUtil::checkInt32($var);
        $this->pagesize = $var;

        return $this;
    }

    /**
     *商户名称
     *
     * Generated from protobuf field <code>string mc_name = 3;</code>
     * @return string
     */
    public function getMcName()
    {
        return $this->mc_name;
    }

    /**
     *商户名称
     *
     * Generated from protobuf field <code>string mc_name = 3;</code>
     * @param string $var
     * @return $this
     */
    public function setMcName($var)
    {
        GPBUtil::checkString($var, True);
        $this->mc_name = $var;

        return $this;
    }

    /**
     *车站
     *
     * Generated from protobuf field <code>int32 station_id = 4;</code>
     * @return int
     */
    public function getStationId()
    {
        return $this->station_id;
    }

    /**
     *车站
     *
     * Generated from protobuf field <code>int32 station_id = 4;</code>
     * @param int $var
     * @return $this
     */
    public function setStationId($var)
    {
        GPBUtil::checkInt32($var);
        $this->station_id = $var;

        return $this;
    }

    /**
     *地址
     *
     * Generated from protobuf field <code>string address = 5;</code>
     * @return string
     */
    public function getAddress()
    {
        return $this->address;
    }

    /**
     *地址
     *
     * Generated from protobuf field <code>string address = 5;</code>
     * @param string $var
     * @return $this
     */
    public function setAddress($var)
    {
        GPBUtil::checkString($var, True);
        $this->address = $var;

        return $this;
    }

    /**
     *商户id
     *
     * Generated from protobuf field <code>int32 merchant_id = 6;</code>
     * @return int
     */
    public function getMerchantId()
    {
        return $this->merchant_id;
    }

    /**
     *商户id
     *
     * Generated from protobuf field <code>int32 merchant_id = 6;</code>
     * @param int $var
     * @return $this
     */
    public function setMerchantId($var)
    {
        GPBUtil::checkInt32($var);
        $this->merchant_id = $var;

        return $this;
    }

}

