<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: merchant/share4.proto

namespace User\Merchant;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 *测试 方法请求参数
 *
 * Generated from protobuf message <code>user.merchant.McTestReq</code>
 */
class McTestReq extends \Google\Protobuf\Internal\Message
{
    /**
     *测试数组1
     *
     * Generated from protobuf field <code>repeated string al = 1;</code>
     */
    private $al;
    /**
     *测试
     *
     * Generated from protobuf field <code>.user.mc_coupData mc_coup = 2;</code>
     */
    private $mc_coup = null;

    public function __construct() {
        \GPBMetadata\Merchant\Share4::initOnce();
        parent::__construct();
    }

    /**
     *测试数组1
     *
     * Generated from protobuf field <code>repeated string al = 1;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getAl()
    {
        return $this->al;
    }

    /**
     *测试数组1
     *
     * Generated from protobuf field <code>repeated string al = 1;</code>
     * @param string[]|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setAl($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::STRING);
        $this->al = $arr;

        return $this;
    }

    /**
     *测试
     *
     * Generated from protobuf field <code>.user.mc_coupData mc_coup = 2;</code>
     * @return \User\mc_coupData
     */
    public function getMcCoup()
    {
        return $this->mc_coup;
    }

    /**
     *测试
     *
     * Generated from protobuf field <code>.user.mc_coupData mc_coup = 2;</code>
     * @param \User\mc_coupData $var
     * @return $this
     */
    public function setMcCoup($var)
    {
        GPBUtil::checkMessage($var, \User\mc_coupData::class);
        $this->mc_coup = $var;

        return $this;
    }

}

