<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: Usertag/share4.proto

namespace User\Usertag;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 *用户标签展示请求
 *
 * Generated from protobuf message <code>user.Usertag.UsertagShowReq</code>
 */
class UsertagShowReq extends \Google\Protobuf\Internal\Message
{
    /**
     *用户id
     *
     * Generated from protobuf field <code>int64 user_id = 1;</code>
     */
    private $user_id = 0;
    /**
     *标签id
     *
     * Generated from protobuf field <code>int64 tag_id = 2;</code>
     */
    private $tag_id = 0;

    public function __construct() {
        \GPBMetadata\Usertag\Share4::initOnce();
        parent::__construct();
    }

    /**
     *用户id
     *
     * Generated from protobuf field <code>int64 user_id = 1;</code>
     * @return int|string
     */
    public function getUserId()
    {
        return $this->user_id;
    }

    /**
     *用户id
     *
     * Generated from protobuf field <code>int64 user_id = 1;</code>
     * @param int|string $var
     * @return $this
     */
    public function setUserId($var)
    {
        GPBUtil::checkInt64($var);
        $this->user_id = $var;

        return $this;
    }

    /**
     *标签id
     *
     * Generated from protobuf field <code>int64 tag_id = 2;</code>
     * @return int|string
     */
    public function getTagId()
    {
        return $this->tag_id;
    }

    /**
     *标签id
     *
     * Generated from protobuf field <code>int64 tag_id = 2;</code>
     * @param int|string $var
     * @return $this
     */
    public function setTagId($var)
    {
        GPBUtil::checkInt64($var);
        $this->tag_id = $var;

        return $this;
    }

}

