<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: Usertag/share4.proto

namespace User\Usertag;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 *用户标签列表展示请求
 *
 * Generated from protobuf message <code>user.Usertag.UsertagListsReq</code>
 */
class UsertagListsReq extends \Google\Protobuf\Internal\Message
{
    /**
     *用户id
     *
     * Generated from protobuf field <code>int64 user_id = 1;</code>
     */
    private $user_id = 0;
    /**
     *标签id
     *
     * Generated from protobuf field <code>int64 tag_id = 2;</code>
     */
    private $tag_id = 0;
    /**
     *页数
     *
     * Generated from protobuf field <code>int32 page = 3;</code>
     */
    private $page = 0;
    /**
     *每页条数
     *
     * Generated from protobuf field <code>int32 pagesize = 4;</code>
     */
    private $pagesize = 0;

    public function __construct() {
        \GPBMetadata\Usertag\Share4::initOnce();
        parent::__construct();
    }

    /**
     *用户id
     *
     * Generated from protobuf field <code>int64 user_id = 1;</code>
     * @return int|string
     */
    public function getUserId()
    {
        return $this->user_id;
    }

    /**
     *用户id
     *
     * Generated from protobuf field <code>int64 user_id = 1;</code>
     * @param int|string $var
     * @return $this
     */
    public function setUserId($var)
    {
        GPBUtil::checkInt64($var);
        $this->user_id = $var;

        return $this;
    }

    /**
     *标签id
     *
     * Generated from protobuf field <code>int64 tag_id = 2;</code>
     * @return int|string
     */
    public function getTagId()
    {
        return $this->tag_id;
    }

    /**
     *标签id
     *
     * Generated from protobuf field <code>int64 tag_id = 2;</code>
     * @param int|string $var
     * @return $this
     */
    public function setTagId($var)
    {
        GPBUtil::checkInt64($var);
        $this->tag_id = $var;

        return $this;
    }

    /**
     *页数
     *
     * Generated from protobuf field <code>int32 page = 3;</code>
     * @return int
     */
    public function getPage()
    {
        return $this->page;
    }

    /**
     *页数
     *
     * Generated from protobuf field <code>int32 page = 3;</code>
     * @param int $var
     * @return $this
     */
    public function setPage($var)
    {
        GPBUtil::checkInt32($var);
        $this->page = $var;

        return $this;
    }

    /**
     *每页条数
     *
     * Generated from protobuf field <code>int32 pagesize = 4;</code>
     * @return int
     */
    public function getPagesize()
    {
        return $this->pagesize;
    }

    /**
     *每页条数
     *
     * Generated from protobuf field <code>int32 pagesize = 4;</code>
     * @param int $var
     * @return $this
     */
    public function setPagesize($var)
    {
        GPBUtil::checkInt32($var);
        $this->pagesize = $var;

        return $this;
    }

}

