<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: share4.proto

namespace User;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 *路由缓存
 *
 * Generated from protobuf message <code>user.ApiauthSetroutecacheData</code>
 */
class ApiauthSetroutecacheData extends \Google\Protobuf\Internal\Message
{
    /**
     *路由id
     *
     * Generated from protobuf field <code>int32 r_id = 1;</code>
     */
    private $r_id = 0;
    /**
     *路由路径
     *
     * Generated from protobuf field <code>string path = 2;</code>
     */
    private $path = '';
    /**
     *微服务类型
     *
     * Generated from protobuf field <code>int32 type_id = 3;</code>
     */
    private $type_id = 0;
    /**
     *创建时间
     *
     * Generated from protobuf field <code>string create_at = 4;</code>
     */
    private $create_at = '';

    public function __construct() {
        \GPBMetadata\Share4::initOnce();
        parent::__construct();
    }

    /**
     *路由id
     *
     * Generated from protobuf field <code>int32 r_id = 1;</code>
     * @return int
     */
    public function getRId()
    {
        return $this->r_id;
    }

    /**
     *路由id
     *
     * Generated from protobuf field <code>int32 r_id = 1;</code>
     * @param int $var
     * @return $this
     */
    public function setRId($var)
    {
        GPBUtil::checkInt32($var);
        $this->r_id = $var;

        return $this;
    }

    /**
     *路由路径
     *
     * Generated from protobuf field <code>string path = 2;</code>
     * @return string
     */
    public function getPath()
    {
        return $this->path;
    }

    /**
     *路由路径
     *
     * Generated from protobuf field <code>string path = 2;</code>
     * @param string $var
     * @return $this
     */
    public function setPath($var)
    {
        GPBUtil::checkString($var, True);
        $this->path = $var;

        return $this;
    }

    /**
     *微服务类型
     *
     * Generated from protobuf field <code>int32 type_id = 3;</code>
     * @return int
     */
    public function getTypeId()
    {
        return $this->type_id;
    }

    /**
     *微服务类型
     *
     * Generated from protobuf field <code>int32 type_id = 3;</code>
     * @param int $var
     * @return $this
     */
    public function setTypeId($var)
    {
        GPBUtil::checkInt32($var);
        $this->type_id = $var;

        return $this;
    }

    /**
     *创建时间
     *
     * Generated from protobuf field <code>string create_at = 4;</code>
     * @return string
     */
    public function getCreateAt()
    {
        return $this->create_at;
    }

    /**
     *创建时间
     *
     * Generated from protobuf field <code>string create_at = 4;</code>
     * @param string $var
     * @return $this
     */
    public function setCreateAt($var)
    {
        GPBUtil::checkString($var, True);
        $this->create_at = $var;

        return $this;
    }

}

