<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: share4.proto

namespace User;

/**
 *枚举类型
 *
 * Protobuf enum <code>User\Enumerate</code>
 */
class Enumerate
{
    /**
     *默认
     *
     * Generated from protobuf enum <code>Null = 0;</code>
     */
    const Null = 0;
    /**
     *oa登陆
     *
     * Generated from protobuf enum <code>OA = 1;</code>
     */
    const OA = 1;
    /**
     *密码登陆
     *
     * Generated from protobuf enum <code>PASSWORD = 2;</code>
     */
    const PASSWORD = 2;
    /**
     *手机号登陆
     *
     * Generated from protobuf enum <code>MOBILE = 3;</code>
     */
    const MOBILE = 3;
    /**
     *包含所有
     *
     * Generated from protobuf enum <code>ALL = 4;</code>
     */
    const ALL = 4;
    /**
     *仅包含
     *
     * Generated from protobuf enum <code>ONLY = 5;</code>
     */
    const ONLY = 5;
    /**
     *不包含
     *
     * Generated from protobuf enum <code>NOTINCLUDE = 6;</code>
     */
    const NOTINCLUDE = 6;
    /**
     *是
     *
     * Generated from protobuf enum <code>Y = 7;</code>
     */
    const Y = 7;
    /**
     *否
     *
     * Generated from protobuf enum <code>N = 8;</code>
     */
    const N = 8;
    /**
     *彩之云登陆
     *
     * Generated from protobuf enum <code>CZY = 9;</code>
     */
    const CZY = 9;
    /**
     *微信登陆
     *
     * Generated from protobuf enum <code>WECHAT = 10;</code>
     */
    const WECHAT = 10;
    /**
     *微信app登陆
     *
     * Generated from protobuf enum <code>WXAPP = 11;</code>
     */
    const WXAPP = 11;
    /**
     *阿里支付
     *
     * Generated from protobuf enum <code>ALIPAY = 12;</code>
     */
    const ALIPAY = 12;
    /**
     *网页登陆
     *
     * Generated from protobuf enum <code>WEB = 13;</code>
     */
    const WEB = 13;
    /**
     *女性
     *
     * Generated from protobuf enum <code>F = 14;</code>
     */
    const F = 14;
    /**
     *男性
     *
     * Generated from protobuf enum <code>M = 15;</code>
     */
    const M = 15;
    /**
     *默认性别
     *
     * Generated from protobuf enum <code>X = 16;</code>
     */
    const X = 16;
}

