<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: share4.proto

namespace User;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 *用户列表结构体数据
 *
 * Generated from protobuf message <code>user.McGetlistData</code>
 */
class McGetlistData extends \Google\Protobuf\Internal\Message
{
    /**
     *商户id
     *
     * Generated from protobuf field <code>int32 merchant_id = 1;</code>
     */
    private $merchant_id = 0;
    /**
     *商户名称
     *
     * Generated from protobuf field <code>string mc_name = 2;</code>
     */
    private $mc_name = '';
    /**
     *合作车场
     *
     * Generated from protobuf field <code>string station_id = 3;</code>
     */
    private $station_id = '';
    /**
     *商户地址
     *
     * Generated from protobuf field <code>string address = 4;</code>
     */
    private $address = '';
    /**
     *商户冻结状态
     *
     * Generated from protobuf field <code>string status = 5;</code>
     */
    private $status = '';
    /**
     *创建时间
     *
     * Generated from protobuf field <code>string create_at = 6;</code>
     */
    private $create_at = '';
    /**
     *更新时间
     *
     * Generated from protobuf field <code>string update_at = 7;</code>
     */
    private $update_at = '';

    public function __construct() {
        \GPBMetadata\Share4::initOnce();
        parent::__construct();
    }

    /**
     *商户id
     *
     * Generated from protobuf field <code>int32 merchant_id = 1;</code>
     * @return int
     */
    public function getMerchantId()
    {
        return $this->merchant_id;
    }

    /**
     *商户id
     *
     * Generated from protobuf field <code>int32 merchant_id = 1;</code>
     * @param int $var
     * @return $this
     */
    public function setMerchantId($var)
    {
        GPBUtil::checkInt32($var);
        $this->merchant_id = $var;

        return $this;
    }

    /**
     *商户名称
     *
     * Generated from protobuf field <code>string mc_name = 2;</code>
     * @return string
     */
    public function getMcName()
    {
        return $this->mc_name;
    }

    /**
     *商户名称
     *
     * Generated from protobuf field <code>string mc_name = 2;</code>
     * @param string $var
     * @return $this
     */
    public function setMcName($var)
    {
        GPBUtil::checkString($var, True);
        $this->mc_name = $var;

        return $this;
    }

    /**
     *合作车场
     *
     * Generated from protobuf field <code>string station_id = 3;</code>
     * @return string
     */
    public function getStationId()
    {
        return $this->station_id;
    }

    /**
     *合作车场
     *
     * Generated from protobuf field <code>string station_id = 3;</code>
     * @param string $var
     * @return $this
     */
    public function setStationId($var)
    {
        GPBUtil::checkString($var, True);
        $this->station_id = $var;

        return $this;
    }

    /**
     *商户地址
     *
     * Generated from protobuf field <code>string address = 4;</code>
     * @return string
     */
    public function getAddress()
    {
        return $this->address;
    }

    /**
     *商户地址
     *
     * Generated from protobuf field <code>string address = 4;</code>
     * @param string $var
     * @return $this
     */
    public function setAddress($var)
    {
        GPBUtil::checkString($var, True);
        $this->address = $var;

        return $this;
    }

    /**
     *商户冻结状态
     *
     * Generated from protobuf field <code>string status = 5;</code>
     * @return string
     */
    public function getStatus()
    {
        return $this->status;
    }

    /**
     *商户冻结状态
     *
     * Generated from protobuf field <code>string status = 5;</code>
     * @param string $var
     * @return $this
     */
    public function setStatus($var)
    {
        GPBUtil::checkString($var, True);
        $this->status = $var;

        return $this;
    }

    /**
     *创建时间
     *
     * Generated from protobuf field <code>string create_at = 6;</code>
     * @return string
     */
    public function getCreateAt()
    {
        return $this->create_at;
    }

    /**
     *创建时间
     *
     * Generated from protobuf field <code>string create_at = 6;</code>
     * @param string $var
     * @return $this
     */
    public function setCreateAt($var)
    {
        GPBUtil::checkString($var, True);
        $this->create_at = $var;

        return $this;
    }

    /**
     *更新时间
     *
     * Generated from protobuf field <code>string update_at = 7;</code>
     * @return string
     */
    public function getUpdateAt()
    {
        return $this->update_at;
    }

    /**
     *更新时间
     *
     * Generated from protobuf field <code>string update_at = 7;</code>
     * @param string $var
     * @return $this
     */
    public function setUpdateAt($var)
    {
        GPBUtil::checkString($var, True);
        $this->update_at = $var;

        return $this;
    }

}

