<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: share4.proto

namespace User;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 *返回结果测试
 *
 * Generated from protobuf message <code>user.McTestData</code>
 */
class McTestData extends \Google\Protobuf\Internal\Message
{
    /**
     *1
     *
     * Generated from protobuf field <code>repeated string al = 1;</code>
     */
    private $al;
    /**
     *1
     *
     * Generated from protobuf field <code>int32 a2 = 2;</code>
     */
    private $a2 = 0;

    public function __construct() {
        \GPBMetadata\Share4::initOnce();
        parent::__construct();
    }

    /**
     *1
     *
     * Generated from protobuf field <code>repeated string al = 1;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getAl()
    {
        return $this->al;
    }

    /**
     *1
     *
     * Generated from protobuf field <code>repeated string al = 1;</code>
     * @param string[]|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setAl($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::STRING);
        $this->al = $arr;

        return $this;
    }

    /**
     *1
     *
     * Generated from protobuf field <code>int32 a2 = 2;</code>
     * @return int
     */
    public function getA2()
    {
        return $this->a2;
    }

    /**
     *1
     *
     * Generated from protobuf field <code>int32 a2 = 2;</code>
     * @param int $var
     * @return $this
     */
    public function setA2($var)
    {
        GPBUtil::checkInt32($var);
        $this->a2 = $var;

        return $this;
    }

}

