<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: share4.proto

namespace User;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 *商户用户信息详情
 *
 * Generated from protobuf message <code>user.McuserShowuserData</code>
 */
class McuserShowuserData extends \Google\Protobuf\Internal\Message
{
    /**
     *商户用户id
     *
     * Generated from protobuf field <code>int32 mcuser_id = 1;</code>
     */
    private $mcuser_id = 0;
    /**
     *商户id
     *
     * Generated from protobuf field <code>int32 merchant_id = 2;</code>
     */
    private $merchant_id = 0;
    /**
     *用户id
     *
     * Generated from protobuf field <code>int64 user_id = 3;</code>
     */
    private $user_id = 0;
    /**
     *角色id
     *
     * Generated from protobuf field <code>int32 role_id = 4;</code>
     */
    private $role_id = 0;
    /**
     *角色类型
     *
     * Generated from protobuf field <code>.user.Enumerate role_type = 5;</code>
     */
    private $role_type = 0;
    /**
     *性别
     *
     * Generated from protobuf field <code>.user.Enumerate sex = 6;</code>
     */
    private $sex = 0;
    /**
     *真实姓名
     *
     * Generated from protobuf field <code>string fullname = 7;</code>
     */
    private $fullname = '';
    /**
     *昵称
     *
     * Generated from protobuf field <code>string nickname = 8;</code>
     */
    private $nickname = '';
    /**
     *用户名
     *
     * Generated from protobuf field <code>string username = 9;</code>
     */
    private $username = '';
    /**
     *手机号
     *
     * Generated from protobuf field <code>string mobile = 10;</code>
     */
    private $mobile = '';
    /**
     *头像
     *
     * Generated from protobuf field <code>string head_img = 11;</code>
     */
    private $head_img = '';
    /**
     *后台id
     *
     * Generated from protobuf field <code>int32 member_id = 12;</code>
     */
    private $member_id = 0;
    /**
     *登陆类型
     *
     * Generated from protobuf field <code>.user.Enumerate type = 13;</code>
     */
    private $type = 0;

    public function __construct() {
        \GPBMetadata\Share4::initOnce();
        parent::__construct();
    }

    /**
     *商户用户id
     *
     * Generated from protobuf field <code>int32 mcuser_id = 1;</code>
     * @return int
     */
    public function getMcuserId()
    {
        return $this->mcuser_id;
    }

    /**
     *商户用户id
     *
     * Generated from protobuf field <code>int32 mcuser_id = 1;</code>
     * @param int $var
     * @return $this
     */
    public function setMcuserId($var)
    {
        GPBUtil::checkInt32($var);
        $this->mcuser_id = $var;

        return $this;
    }

    /**
     *商户id
     *
     * Generated from protobuf field <code>int32 merchant_id = 2;</code>
     * @return int
     */
    public function getMerchantId()
    {
        return $this->merchant_id;
    }

    /**
     *商户id
     *
     * Generated from protobuf field <code>int32 merchant_id = 2;</code>
     * @param int $var
     * @return $this
     */
    public function setMerchantId($var)
    {
        GPBUtil::checkInt32($var);
        $this->merchant_id = $var;

        return $this;
    }

    /**
     *用户id
     *
     * Generated from protobuf field <code>int64 user_id = 3;</code>
     * @return int|string
     */
    public function getUserId()
    {
        return $this->user_id;
    }

    /**
     *用户id
     *
     * Generated from protobuf field <code>int64 user_id = 3;</code>
     * @param int|string $var
     * @return $this
     */
    public function setUserId($var)
    {
        GPBUtil::checkInt64($var);
        $this->user_id = $var;

        return $this;
    }

    /**
     *角色id
     *
     * Generated from protobuf field <code>int32 role_id = 4;</code>
     * @return int
     */
    public function getRoleId()
    {
        return $this->role_id;
    }

    /**
     *角色id
     *
     * Generated from protobuf field <code>int32 role_id = 4;</code>
     * @param int $var
     * @return $this
     */
    public function setRoleId($var)
    {
        GPBUtil::checkInt32($var);
        $this->role_id = $var;

        return $this;
    }

    /**
     *角色类型
     *
     * Generated from protobuf field <code>.user.Enumerate role_type = 5;</code>
     * @return int
     */
    public function getRoleType()
    {
        return $this->role_type;
    }

    /**
     *角色类型
     *
     * Generated from protobuf field <code>.user.Enumerate role_type = 5;</code>
     * @param int $var
     * @return $this
     */
    public function setRoleType($var)
    {
        GPBUtil::checkEnum($var, \User\Enumerate::class);
        $this->role_type = $var;

        return $this;
    }

    /**
     *性别
     *
     * Generated from protobuf field <code>.user.Enumerate sex = 6;</code>
     * @return int
     */
    public function getSex()
    {
        return $this->sex;
    }

    /**
     *性别
     *
     * Generated from protobuf field <code>.user.Enumerate sex = 6;</code>
     * @param int $var
     * @return $this
     */
    public function setSex($var)
    {
        GPBUtil::checkEnum($var, \User\Enumerate::class);
        $this->sex = $var;

        return $this;
    }

    /**
     *真实姓名
     *
     * Generated from protobuf field <code>string fullname = 7;</code>
     * @return string
     */
    public function getFullname()
    {
        return $this->fullname;
    }

    /**
     *真实姓名
     *
     * Generated from protobuf field <code>string fullname = 7;</code>
     * @param string $var
     * @return $this
     */
    public function setFullname($var)
    {
        GPBUtil::checkString($var, True);
        $this->fullname = $var;

        return $this;
    }

    /**
     *昵称
     *
     * Generated from protobuf field <code>string nickname = 8;</code>
     * @return string
     */
    public function getNickname()
    {
        return $this->nickname;
    }

    /**
     *昵称
     *
     * Generated from protobuf field <code>string nickname = 8;</code>
     * @param string $var
     * @return $this
     */
    public function setNickname($var)
    {
        GPBUtil::checkString($var, True);
        $this->nickname = $var;

        return $this;
    }

    /**
     *用户名
     *
     * Generated from protobuf field <code>string username = 9;</code>
     * @return string
     */
    public function getUsername()
    {
        return $this->username;
    }

    /**
     *用户名
     *
     * Generated from protobuf field <code>string username = 9;</code>
     * @param string $var
     * @return $this
     */
    public function setUsername($var)
    {
        GPBUtil::checkString($var, True);
        $this->username = $var;

        return $this;
    }

    /**
     *手机号
     *
     * Generated from protobuf field <code>string mobile = 10;</code>
     * @return string
     */
    public function getMobile()
    {
        return $this->mobile;
    }

    /**
     *手机号
     *
     * Generated from protobuf field <code>string mobile = 10;</code>
     * @param string $var
     * @return $this
     */
    public function setMobile($var)
    {
        GPBUtil::checkString($var, True);
        $this->mobile = $var;

        return $this;
    }

    /**
     *头像
     *
     * Generated from protobuf field <code>string head_img = 11;</code>
     * @return string
     */
    public function getHeadImg()
    {
        return $this->head_img;
    }

    /**
     *头像
     *
     * Generated from protobuf field <code>string head_img = 11;</code>
     * @param string $var
     * @return $this
     */
    public function setHeadImg($var)
    {
        GPBUtil::checkString($var, True);
        $this->head_img = $var;

        return $this;
    }

    /**
     *后台id
     *
     * Generated from protobuf field <code>int32 member_id = 12;</code>
     * @return int
     */
    public function getMemberId()
    {
        return $this->member_id;
    }

    /**
     *后台id
     *
     * Generated from protobuf field <code>int32 member_id = 12;</code>
     * @param int $var
     * @return $this
     */
    public function setMemberId($var)
    {
        GPBUtil::checkInt32($var);
        $this->member_id = $var;

        return $this;
    }

    /**
     *登陆类型
     *
     * Generated from protobuf field <code>.user.Enumerate type = 13;</code>
     * @return int
     */
    public function getType()
    {
        return $this->type;
    }

    /**
     *登陆类型
     *
     * Generated from protobuf field <code>.user.Enumerate type = 13;</code>
     * @param int $var
     * @return $this
     */
    public function setType($var)
    {
        GPBUtil::checkEnum($var, \User\Enumerate::class);
        $this->type = $var;

        return $this;
    }

}

