<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: share4.proto

namespace User;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 *后台数据展示
 *
 * Generated from protobuf message <code>user.MemberShowData</code>
 */
class MemberShowData extends \Google\Protobuf\Internal\Message
{
    /**
     *后台id
     *
     * Generated from protobuf field <code>int32 member_id = 1;</code>
     */
    private $member_id = 0;
    /**
     *用户id
     *
     * Generated from protobuf field <code>int64 user_id = 2;</code>
     */
    private $user_id = 0;
    /**
     *用户类型
     *
     * Generated from protobuf field <code>.user.Enumerate type = 3;</code>
     */
    private $type = 0;
    /**
     *密码
     *
     * Generated from protobuf field <code>string password = 4;</code>
     */
    private $password = '';
    /**
     *oa账号
     *
     * Generated from protobuf field <code>string oa = 5;</code>
     */
    private $oa = '';
    /**
     *角色id
     *
     * Generated from protobuf field <code>string role_id = 6;</code>
     */
    private $role_id = '';
    /**
     *后台类型
     *
     * Generated from protobuf field <code>string role_type = 7;</code>
     */
    private $role_type = '';
    /**
     *公司
     *
     * Generated from protobuf field <code>string companies = 8;</code>
     */
    private $companies = '';
    /**
     *上次登陆时间
     *
     * Generated from protobuf field <code>string last_login_time = 9;</code>
     */
    private $last_login_time = '';
    /**
     *上次登陆ip
     *
     * Generated from protobuf field <code>string last_login_ip = 10;</code>
     */
    private $last_login_ip = '';
    /**
     *创建时间
     *
     * Generated from protobuf field <code>string create_at = 11;</code>
     */
    private $create_at = '';
    /**
     *更新时间
     *
     * Generated from protobuf field <code>string update_at = 12;</code>
     */
    private $update_at = '';
    /**
     *是否锁定
     *
     * Generated from protobuf field <code>.user.Enumerate is_lock = 13;</code>
     */
    private $is_lock = 0;
    /**
     *部门
     *
     * Generated from protobuf field <code>string dept = 14;</code>
     */
    private $dept = '';
    /**
     *附加信息
     *
     * Generated from protobuf field <code>string attach = 15;</code>
     */
    private $attach = '';
    /**
     *是否自动登录
     *
     * Generated from protobuf field <code>.user.Enumerate is_auto_login = 16;</code>
     */
    private $is_auto_login = 0;

    public function __construct() {
        \GPBMetadata\Share4::initOnce();
        parent::__construct();
    }

    /**
     *后台id
     *
     * Generated from protobuf field <code>int32 member_id = 1;</code>
     * @return int
     */
    public function getMemberId()
    {
        return $this->member_id;
    }

    /**
     *后台id
     *
     * Generated from protobuf field <code>int32 member_id = 1;</code>
     * @param int $var
     * @return $this
     */
    public function setMemberId($var)
    {
        GPBUtil::checkInt32($var);
        $this->member_id = $var;

        return $this;
    }

    /**
     *用户id
     *
     * Generated from protobuf field <code>int64 user_id = 2;</code>
     * @return int|string
     */
    public function getUserId()
    {
        return $this->user_id;
    }

    /**
     *用户id
     *
     * Generated from protobuf field <code>int64 user_id = 2;</code>
     * @param int|string $var
     * @return $this
     */
    public function setUserId($var)
    {
        GPBUtil::checkInt64($var);
        $this->user_id = $var;

        return $this;
    }

    /**
     *用户类型
     *
     * Generated from protobuf field <code>.user.Enumerate type = 3;</code>
     * @return int
     */
    public function getType()
    {
        return $this->type;
    }

    /**
     *用户类型
     *
     * Generated from protobuf field <code>.user.Enumerate type = 3;</code>
     * @param int $var
     * @return $this
     */
    public function setType($var)
    {
        GPBUtil::checkEnum($var, \User\Enumerate::class);
        $this->type = $var;

        return $this;
    }

    /**
     *密码
     *
     * Generated from protobuf field <code>string password = 4;</code>
     * @return string
     */
    public function getPassword()
    {
        return $this->password;
    }

    /**
     *密码
     *
     * Generated from protobuf field <code>string password = 4;</code>
     * @param string $var
     * @return $this
     */
    public function setPassword($var)
    {
        GPBUtil::checkString($var, True);
        $this->password = $var;

        return $this;
    }

    /**
     *oa账号
     *
     * Generated from protobuf field <code>string oa = 5;</code>
     * @return string
     */
    public function getOa()
    {
        return $this->oa;
    }

    /**
     *oa账号
     *
     * Generated from protobuf field <code>string oa = 5;</code>
     * @param string $var
     * @return $this
     */
    public function setOa($var)
    {
        GPBUtil::checkString($var, True);
        $this->oa = $var;

        return $this;
    }

    /**
     *角色id
     *
     * Generated from protobuf field <code>string role_id = 6;</code>
     * @return string
     */
    public function getRoleId()
    {
        return $this->role_id;
    }

    /**
     *角色id
     *
     * Generated from protobuf field <code>string role_id = 6;</code>
     * @param string $var
     * @return $this
     */
    public function setRoleId($var)
    {
        GPBUtil::checkString($var, True);
        $this->role_id = $var;

        return $this;
    }

    /**
     *后台类型
     *
     * Generated from protobuf field <code>string role_type = 7;</code>
     * @return string
     */
    public function getRoleType()
    {
        return $this->role_type;
    }

    /**
     *后台类型
     *
     * Generated from protobuf field <code>string role_type = 7;</code>
     * @param string $var
     * @return $this
     */
    public function setRoleType($var)
    {
        GPBUtil::checkString($var, True);
        $this->role_type = $var;

        return $this;
    }

    /**
     *公司
     *
     * Generated from protobuf field <code>string companies = 8;</code>
     * @return string
     */
    public function getCompanies()
    {
        return $this->companies;
    }

    /**
     *公司
     *
     * Generated from protobuf field <code>string companies = 8;</code>
     * @param string $var
     * @return $this
     */
    public function setCompanies($var)
    {
        GPBUtil::checkString($var, True);
        $this->companies = $var;

        return $this;
    }

    /**
     *上次登陆时间
     *
     * Generated from protobuf field <code>string last_login_time = 9;</code>
     * @return string
     */
    public function getLastLoginTime()
    {
        return $this->last_login_time;
    }

    /**
     *上次登陆时间
     *
     * Generated from protobuf field <code>string last_login_time = 9;</code>
     * @param string $var
     * @return $this
     */
    public function setLastLoginTime($var)
    {
        GPBUtil::checkString($var, True);
        $this->last_login_time = $var;

        return $this;
    }

    /**
     *上次登陆ip
     *
     * Generated from protobuf field <code>string last_login_ip = 10;</code>
     * @return string
     */
    public function getLastLoginIp()
    {
        return $this->last_login_ip;
    }

    /**
     *上次登陆ip
     *
     * Generated from protobuf field <code>string last_login_ip = 10;</code>
     * @param string $var
     * @return $this
     */
    public function setLastLoginIp($var)
    {
        GPBUtil::checkString($var, True);
        $this->last_login_ip = $var;

        return $this;
    }

    /**
     *创建时间
     *
     * Generated from protobuf field <code>string create_at = 11;</code>
     * @return string
     */
    public function getCreateAt()
    {
        return $this->create_at;
    }

    /**
     *创建时间
     *
     * Generated from protobuf field <code>string create_at = 11;</code>
     * @param string $var
     * @return $this
     */
    public function setCreateAt($var)
    {
        GPBUtil::checkString($var, True);
        $this->create_at = $var;

        return $this;
    }

    /**
     *更新时间
     *
     * Generated from protobuf field <code>string update_at = 12;</code>
     * @return string
     */
    public function getUpdateAt()
    {
        return $this->update_at;
    }

    /**
     *更新时间
     *
     * Generated from protobuf field <code>string update_at = 12;</code>
     * @param string $var
     * @return $this
     */
    public function setUpdateAt($var)
    {
        GPBUtil::checkString($var, True);
        $this->update_at = $var;

        return $this;
    }

    /**
     *是否锁定
     *
     * Generated from protobuf field <code>.user.Enumerate is_lock = 13;</code>
     * @return int
     */
    public function getIsLock()
    {
        return $this->is_lock;
    }

    /**
     *是否锁定
     *
     * Generated from protobuf field <code>.user.Enumerate is_lock = 13;</code>
     * @param int $var
     * @return $this
     */
    public function setIsLock($var)
    {
        GPBUtil::checkEnum($var, \User\Enumerate::class);
        $this->is_lock = $var;

        return $this;
    }

    /**
     *部门
     *
     * Generated from protobuf field <code>string dept = 14;</code>
     * @return string
     */
    public function getDept()
    {
        return $this->dept;
    }

    /**
     *部门
     *
     * Generated from protobuf field <code>string dept = 14;</code>
     * @param string $var
     * @return $this
     */
    public function setDept($var)
    {
        GPBUtil::checkString($var, True);
        $this->dept = $var;

        return $this;
    }

    /**
     *附加信息
     *
     * Generated from protobuf field <code>string attach = 15;</code>
     * @return string
     */
    public function getAttach()
    {
        return $this->attach;
    }

    /**
     *附加信息
     *
     * Generated from protobuf field <code>string attach = 15;</code>
     * @param string $var
     * @return $this
     */
    public function setAttach($var)
    {
        GPBUtil::checkString($var, True);
        $this->attach = $var;

        return $this;
    }

    /**
     *是否自动登录
     *
     * Generated from protobuf field <code>.user.Enumerate is_auto_login = 16;</code>
     * @return int
     */
    public function getIsAutoLogin()
    {
        return $this->is_auto_login;
    }

    /**
     *是否自动登录
     *
     * Generated from protobuf field <code>.user.Enumerate is_auto_login = 16;</code>
     * @param int $var
     * @return $this
     */
    public function setIsAutoLogin($var)
    {
        GPBUtil::checkEnum($var, \User\Enumerate::class);
        $this->is_auto_login = $var;

        return $this;
    }

}

