<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: share4.proto

namespace User;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 *后台用户展示
 *
 * Generated from protobuf message <code>user.MemberShowUserData</code>
 */
class MemberShowUserData extends \Google\Protobuf\Internal\Message
{
    /**
     *后台id
     *
     * Generated from protobuf field <code>int32 member_id = 1;</code>
     */
    private $member_id = 0;
    /**
     *角色id
     *
     * Generated from protobuf field <code>string role_id = 2;</code>
     */
    private $role_id = '';
    /**
     *用户id
     *
     * Generated from protobuf field <code>int64 user_id = 3;</code>
     */
    private $user_id = 0;
    /**
     *用户状态
     *
     * Generated from protobuf field <code>.user.Enumerate status = 4;</code>
     */
    private $status = 0;
    /**
     *用户性别
     *
     * Generated from protobuf field <code>.user.Enumerate sex = 5;</code>
     */
    private $sex = 0;
    /**
     *全名
     *
     * Generated from protobuf field <code>string fullname = 6;</code>
     */
    private $fullname = '';
    /**
     *昵称
     *
     * Generated from protobuf field <code>string nickname = 7;</code>
     */
    private $nickname = '';
    /**
     *用户名
     *
     * Generated from protobuf field <code>string username = 8;</code>
     */
    private $username = '';
    /**
     *手机号
     *
     * Generated from protobuf field <code>string mobile = 9;</code>
     */
    private $mobile = '';
    /**
     *是否锁定
     *
     * Generated from protobuf field <code>.user.Enumerate is_lock = 10;</code>
     */
    private $is_lock = 0;
    /**
     *公司
     *
     * Generated from protobuf field <code>string companies = 11;</code>
     */
    private $companies = '';
    /**
     *oa账号
     *
     * Generated from protobuf field <code>string oa = 12;</code>
     */
    private $oa = '';
    /**
     *账户类型
     *
     * Generated from protobuf field <code>.user.Enumerate type = 13;</code>
     */
    private $type = 0;
    /**
     *电子邮箱
     *
     * Generated from protobuf field <code>string email = 14;</code>
     */
    private $email = '';
    /**
     *自动锁定
     *
     * Generated from protobuf field <code>.user.Enumerate autolock = 15;</code>
     */
    private $autolock = 0;
    /**
     *是否验证
     *
     * Generated from protobuf field <code>.user.Enumerate verify = 16;</code>
     */
    private $verify = 0;
    /**
     *账户类型
     *
     * Generated from protobuf field <code>string role_type = 17;</code>
     */
    private $role_type = '';
    /**
     *附加信息
     *
     * Generated from protobuf field <code>string attach = 18;</code>
     */
    private $attach = '';
    /**
     *部门
     *
     * Generated from protobuf field <code>string dept = 19;</code>
     */
    private $dept = '';
    /**
     *是否自动登录
     *
     * Generated from protobuf field <code>.user.Enumerate is_auto_login = 20;</code>
     */
    private $is_auto_login = 0;

    public function __construct() {
        \GPBMetadata\Share4::initOnce();
        parent::__construct();
    }

    /**
     *后台id
     *
     * Generated from protobuf field <code>int32 member_id = 1;</code>
     * @return int
     */
    public function getMemberId()
    {
        return $this->member_id;
    }

    /**
     *后台id
     *
     * Generated from protobuf field <code>int32 member_id = 1;</code>
     * @param int $var
     * @return $this
     */
    public function setMemberId($var)
    {
        GPBUtil::checkInt32($var);
        $this->member_id = $var;

        return $this;
    }

    /**
     *角色id
     *
     * Generated from protobuf field <code>string role_id = 2;</code>
     * @return string
     */
    public function getRoleId()
    {
        return $this->role_id;
    }

    /**
     *角色id
     *
     * Generated from protobuf field <code>string role_id = 2;</code>
     * @param string $var
     * @return $this
     */
    public function setRoleId($var)
    {
        GPBUtil::checkString($var, True);
        $this->role_id = $var;

        return $this;
    }

    /**
     *用户id
     *
     * Generated from protobuf field <code>int64 user_id = 3;</code>
     * @return int|string
     */
    public function getUserId()
    {
        return $this->user_id;
    }

    /**
     *用户id
     *
     * Generated from protobuf field <code>int64 user_id = 3;</code>
     * @param int|string $var
     * @return $this
     */
    public function setUserId($var)
    {
        GPBUtil::checkInt64($var);
        $this->user_id = $var;

        return $this;
    }

    /**
     *用户状态
     *
     * Generated from protobuf field <code>.user.Enumerate status = 4;</code>
     * @return int
     */
    public function getStatus()
    {
        return $this->status;
    }

    /**
     *用户状态
     *
     * Generated from protobuf field <code>.user.Enumerate status = 4;</code>
     * @param int $var
     * @return $this
     */
    public function setStatus($var)
    {
        GPBUtil::checkEnum($var, \User\Enumerate::class);
        $this->status = $var;

        return $this;
    }

    /**
     *用户性别
     *
     * Generated from protobuf field <code>.user.Enumerate sex = 5;</code>
     * @return int
     */
    public function getSex()
    {
        return $this->sex;
    }

    /**
     *用户性别
     *
     * Generated from protobuf field <code>.user.Enumerate sex = 5;</code>
     * @param int $var
     * @return $this
     */
    public function setSex($var)
    {
        GPBUtil::checkEnum($var, \User\Enumerate::class);
        $this->sex = $var;

        return $this;
    }

    /**
     *全名
     *
     * Generated from protobuf field <code>string fullname = 6;</code>
     * @return string
     */
    public function getFullname()
    {
        return $this->fullname;
    }

    /**
     *全名
     *
     * Generated from protobuf field <code>string fullname = 6;</code>
     * @param string $var
     * @return $this
     */
    public function setFullname($var)
    {
        GPBUtil::checkString($var, True);
        $this->fullname = $var;

        return $this;
    }

    /**
     *昵称
     *
     * Generated from protobuf field <code>string nickname = 7;</code>
     * @return string
     */
    public function getNickname()
    {
        return $this->nickname;
    }

    /**
     *昵称
     *
     * Generated from protobuf field <code>string nickname = 7;</code>
     * @param string $var
     * @return $this
     */
    public function setNickname($var)
    {
        GPBUtil::checkString($var, True);
        $this->nickname = $var;

        return $this;
    }

    /**
     *用户名
     *
     * Generated from protobuf field <code>string username = 8;</code>
     * @return string
     */
    public function getUsername()
    {
        return $this->username;
    }

    /**
     *用户名
     *
     * Generated from protobuf field <code>string username = 8;</code>
     * @param string $var
     * @return $this
     */
    public function setUsername($var)
    {
        GPBUtil::checkString($var, True);
        $this->username = $var;

        return $this;
    }

    /**
     *手机号
     *
     * Generated from protobuf field <code>string mobile = 9;</code>
     * @return string
     */
    public function getMobile()
    {
        return $this->mobile;
    }

    /**
     *手机号
     *
     * Generated from protobuf field <code>string mobile = 9;</code>
     * @param string $var
     * @return $this
     */
    public function setMobile($var)
    {
        GPBUtil::checkString($var, True);
        $this->mobile = $var;

        return $this;
    }

    /**
     *是否锁定
     *
     * Generated from protobuf field <code>.user.Enumerate is_lock = 10;</code>
     * @return int
     */
    public function getIsLock()
    {
        return $this->is_lock;
    }

    /**
     *是否锁定
     *
     * Generated from protobuf field <code>.user.Enumerate is_lock = 10;</code>
     * @param int $var
     * @return $this
     */
    public function setIsLock($var)
    {
        GPBUtil::checkEnum($var, \User\Enumerate::class);
        $this->is_lock = $var;

        return $this;
    }

    /**
     *公司
     *
     * Generated from protobuf field <code>string companies = 11;</code>
     * @return string
     */
    public function getCompanies()
    {
        return $this->companies;
    }

    /**
     *公司
     *
     * Generated from protobuf field <code>string companies = 11;</code>
     * @param string $var
     * @return $this
     */
    public function setCompanies($var)
    {
        GPBUtil::checkString($var, True);
        $this->companies = $var;

        return $this;
    }

    /**
     *oa账号
     *
     * Generated from protobuf field <code>string oa = 12;</code>
     * @return string
     */
    public function getOa()
    {
        return $this->oa;
    }

    /**
     *oa账号
     *
     * Generated from protobuf field <code>string oa = 12;</code>
     * @param string $var
     * @return $this
     */
    public function setOa($var)
    {
        GPBUtil::checkString($var, True);
        $this->oa = $var;

        return $this;
    }

    /**
     *账户类型
     *
     * Generated from protobuf field <code>.user.Enumerate type = 13;</code>
     * @return int
     */
    public function getType()
    {
        return $this->type;
    }

    /**
     *账户类型
     *
     * Generated from protobuf field <code>.user.Enumerate type = 13;</code>
     * @param int $var
     * @return $this
     */
    public function setType($var)
    {
        GPBUtil::checkEnum($var, \User\Enumerate::class);
        $this->type = $var;

        return $this;
    }

    /**
     *电子邮箱
     *
     * Generated from protobuf field <code>string email = 14;</code>
     * @return string
     */
    public function getEmail()
    {
        return $this->email;
    }

    /**
     *电子邮箱
     *
     * Generated from protobuf field <code>string email = 14;</code>
     * @param string $var
     * @return $this
     */
    public function setEmail($var)
    {
        GPBUtil::checkString($var, True);
        $this->email = $var;

        return $this;
    }

    /**
     *自动锁定
     *
     * Generated from protobuf field <code>.user.Enumerate autolock = 15;</code>
     * @return int
     */
    public function getAutolock()
    {
        return $this->autolock;
    }

    /**
     *自动锁定
     *
     * Generated from protobuf field <code>.user.Enumerate autolock = 15;</code>
     * @param int $var
     * @return $this
     */
    public function setAutolock($var)
    {
        GPBUtil::checkEnum($var, \User\Enumerate::class);
        $this->autolock = $var;

        return $this;
    }

    /**
     *是否验证
     *
     * Generated from protobuf field <code>.user.Enumerate verify = 16;</code>
     * @return int
     */
    public function getVerify()
    {
        return $this->verify;
    }

    /**
     *是否验证
     *
     * Generated from protobuf field <code>.user.Enumerate verify = 16;</code>
     * @param int $var
     * @return $this
     */
    public function setVerify($var)
    {
        GPBUtil::checkEnum($var, \User\Enumerate::class);
        $this->verify = $var;

        return $this;
    }

    /**
     *账户类型
     *
     * Generated from protobuf field <code>string role_type = 17;</code>
     * @return string
     */
    public function getRoleType()
    {
        return $this->role_type;
    }

    /**
     *账户类型
     *
     * Generated from protobuf field <code>string role_type = 17;</code>
     * @param string $var
     * @return $this
     */
    public function setRoleType($var)
    {
        GPBUtil::checkString($var, True);
        $this->role_type = $var;

        return $this;
    }

    /**
     *附加信息
     *
     * Generated from protobuf field <code>string attach = 18;</code>
     * @return string
     */
    public function getAttach()
    {
        return $this->attach;
    }

    /**
     *附加信息
     *
     * Generated from protobuf field <code>string attach = 18;</code>
     * @param string $var
     * @return $this
     */
    public function setAttach($var)
    {
        GPBUtil::checkString($var, True);
        $this->attach = $var;

        return $this;
    }

    /**
     *部门
     *
     * Generated from protobuf field <code>string dept = 19;</code>
     * @return string
     */
    public function getDept()
    {
        return $this->dept;
    }

    /**
     *部门
     *
     * Generated from protobuf field <code>string dept = 19;</code>
     * @param string $var
     * @return $this
     */
    public function setDept($var)
    {
        GPBUtil::checkString($var, True);
        $this->dept = $var;

        return $this;
    }

    /**
     *是否自动登录
     *
     * Generated from protobuf field <code>.user.Enumerate is_auto_login = 20;</code>
     * @return int
     */
    public function getIsAutoLogin()
    {
        return $this->is_auto_login;
    }

    /**
     *是否自动登录
     *
     * Generated from protobuf field <code>.user.Enumerate is_auto_login = 20;</code>
     * @param int $var
     * @return $this
     */
    public function setIsAutoLogin($var)
    {
        GPBUtil::checkEnum($var, \User\Enumerate::class);
        $this->is_auto_login = $var;

        return $this;
    }

}

