<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: share4.proto

namespace User;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 *展示客户信息响应数组
 *
 * Generated from protobuf message <code>user.ShowClientData</code>
 */
class ShowClientData extends \Google\Protobuf\Internal\Message
{
    /**
     *客户端id
     *
     * Generated from protobuf field <code>int32 client_id = 1;</code>
     */
    private $client_id = 0;
    /**
     *用户id
     *
     * Generated from protobuf field <code>int64 user_id = 2;</code>
     */
    private $user_id = 0;
    /**
     *客户端类型
     *
     * Generated from protobuf field <code>.user.Enumerate kind = 3;</code>
     */
    private $kind = 0;
    /**
     *应用id
     *
     * Generated from protobuf field <code>string app_id = 4;</code>
     */
    private $app_id = '';
    /**
     *授权id
     *
     * Generated from protobuf field <code>string openid = 5;</code>
     */
    private $openid = '';
    /**
     *创建时间
     *
     * Generated from protobuf field <code>string create_at = 6;</code>
     */
    private $create_at = '';
    /**
     *更新时间
     *
     * Generated from protobuf field <code>string update_at = 7;</code>
     */
    private $update_at = '';

    public function __construct() {
        \GPBMetadata\Share4::initOnce();
        parent::__construct();
    }

    /**
     *客户端id
     *
     * Generated from protobuf field <code>int32 client_id = 1;</code>
     * @return int
     */
    public function getClientId()
    {
        return $this->client_id;
    }

    /**
     *客户端id
     *
     * Generated from protobuf field <code>int32 client_id = 1;</code>
     * @param int $var
     * @return $this
     */
    public function setClientId($var)
    {
        GPBUtil::checkInt32($var);
        $this->client_id = $var;

        return $this;
    }

    /**
     *用户id
     *
     * Generated from protobuf field <code>int64 user_id = 2;</code>
     * @return int|string
     */
    public function getUserId()
    {
        return $this->user_id;
    }

    /**
     *用户id
     *
     * Generated from protobuf field <code>int64 user_id = 2;</code>
     * @param int|string $var
     * @return $this
     */
    public function setUserId($var)
    {
        GPBUtil::checkInt64($var);
        $this->user_id = $var;

        return $this;
    }

    /**
     *客户端类型
     *
     * Generated from protobuf field <code>.user.Enumerate kind = 3;</code>
     * @return int
     */
    public function getKind()
    {
        return $this->kind;
    }

    /**
     *客户端类型
     *
     * Generated from protobuf field <code>.user.Enumerate kind = 3;</code>
     * @param int $var
     * @return $this
     */
    public function setKind($var)
    {
        GPBUtil::checkEnum($var, \User\Enumerate::class);
        $this->kind = $var;

        return $this;
    }

    /**
     *应用id
     *
     * Generated from protobuf field <code>string app_id = 4;</code>
     * @return string
     */
    public function getAppId()
    {
        return $this->app_id;
    }

    /**
     *应用id
     *
     * Generated from protobuf field <code>string app_id = 4;</code>
     * @param string $var
     * @return $this
     */
    public function setAppId($var)
    {
        GPBUtil::checkString($var, True);
        $this->app_id = $var;

        return $this;
    }

    /**
     *授权id
     *
     * Generated from protobuf field <code>string openid = 5;</code>
     * @return string
     */
    public function getOpenid()
    {
        return $this->openid;
    }

    /**
     *授权id
     *
     * Generated from protobuf field <code>string openid = 5;</code>
     * @param string $var
     * @return $this
     */
    public function setOpenid($var)
    {
        GPBUtil::checkString($var, True);
        $this->openid = $var;

        return $this;
    }

    /**
     *创建时间
     *
     * Generated from protobuf field <code>string create_at = 6;</code>
     * @return string
     */
    public function getCreateAt()
    {
        return $this->create_at;
    }

    /**
     *创建时间
     *
     * Generated from protobuf field <code>string create_at = 6;</code>
     * @param string $var
     * @return $this
     */
    public function setCreateAt($var)
    {
        GPBUtil::checkString($var, True);
        $this->create_at = $var;

        return $this;
    }

    /**
     *更新时间
     *
     * Generated from protobuf field <code>string update_at = 7;</code>
     * @return string
     */
    public function getUpdateAt()
    {
        return $this->update_at;
    }

    /**
     *更新时间
     *
     * Generated from protobuf field <code>string update_at = 7;</code>
     * @param string $var
     * @return $this
     */
    public function setUpdateAt($var)
    {
        GPBUtil::checkString($var, True);
        $this->update_at = $var;

        return $this;
    }

}

