<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: share4.proto

namespace User;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 *用户列表数据
 *
 * Generated from protobuf message <code>user.UserListsData</code>
 */
class UserListsData extends \Google\Protobuf\Internal\Message
{
    /**
     *用户id
     *
     * Generated from protobuf field <code>int64 user_id = 1;</code>
     */
    private $user_id = 0;
    /**
     *性别
     *
     * Generated from protobuf field <code>.user.Enumerate sex = 2;</code>
     */
    private $sex = 0;
    /**
     *真实姓名
     *
     * Generated from protobuf field <code>string fullname = 3;</code>
     */
    private $fullname = '';
    /**
     *昵称
     *
     * Generated from protobuf field <code>string nickname = 4;</code>
     */
    private $nickname = '';
    /**
     *用户名
     *
     * Generated from protobuf field <code>string username = 5;</code>
     */
    private $username = '';
    /**
     *手机号
     *
     * Generated from protobuf field <code>string mobile = 6;</code>
     */
    private $mobile = '';
    /**
     *用户头像
     *
     * Generated from protobuf field <code>string head_img = 7;</code>
     */
    private $head_img = '';
    /**
     *用户状态
     *
     * Generated from protobuf field <code>.user.Enumerate status = 8;</code>
     */
    private $status = 0;
    /**
     *自动锁定
     *
     * Generated from protobuf field <code>.user.Enumerate autolock = 9;</code>
     */
    private $autolock = 0;
    /**
     *是否验证
     *
     * Generated from protobuf field <code>.user.Enumerate verify = 10;</code>
     */
    private $verify = 0;
    /**
     *创建时间
     *
     * Generated from protobuf field <code>string create_at = 11;</code>
     */
    private $create_at = '';
    /**
     *更新时间
     *
     * Generated from protobuf field <code>string update_at = 12;</code>
     */
    private $update_at = '';
    /**
     *电子邮箱
     *
     * Generated from protobuf field <code>string email = 13;</code>
     */
    private $email = '';

    public function __construct() {
        \GPBMetadata\Share4::initOnce();
        parent::__construct();
    }

    /**
     *用户id
     *
     * Generated from protobuf field <code>int64 user_id = 1;</code>
     * @return int|string
     */
    public function getUserId()
    {
        return $this->user_id;
    }

    /**
     *用户id
     *
     * Generated from protobuf field <code>int64 user_id = 1;</code>
     * @param int|string $var
     * @return $this
     */
    public function setUserId($var)
    {
        GPBUtil::checkInt64($var);
        $this->user_id = $var;

        return $this;
    }

    /**
     *性别
     *
     * Generated from protobuf field <code>.user.Enumerate sex = 2;</code>
     * @return int
     */
    public function getSex()
    {
        return $this->sex;
    }

    /**
     *性别
     *
     * Generated from protobuf field <code>.user.Enumerate sex = 2;</code>
     * @param int $var
     * @return $this
     */
    public function setSex($var)
    {
        GPBUtil::checkEnum($var, \User\Enumerate::class);
        $this->sex = $var;

        return $this;
    }

    /**
     *真实姓名
     *
     * Generated from protobuf field <code>string fullname = 3;</code>
     * @return string
     */
    public function getFullname()
    {
        return $this->fullname;
    }

    /**
     *真实姓名
     *
     * Generated from protobuf field <code>string fullname = 3;</code>
     * @param string $var
     * @return $this
     */
    public function setFullname($var)
    {
        GPBUtil::checkString($var, True);
        $this->fullname = $var;

        return $this;
    }

    /**
     *昵称
     *
     * Generated from protobuf field <code>string nickname = 4;</code>
     * @return string
     */
    public function getNickname()
    {
        return $this->nickname;
    }

    /**
     *昵称
     *
     * Generated from protobuf field <code>string nickname = 4;</code>
     * @param string $var
     * @return $this
     */
    public function setNickname($var)
    {
        GPBUtil::checkString($var, True);
        $this->nickname = $var;

        return $this;
    }

    /**
     *用户名
     *
     * Generated from protobuf field <code>string username = 5;</code>
     * @return string
     */
    public function getUsername()
    {
        return $this->username;
    }

    /**
     *用户名
     *
     * Generated from protobuf field <code>string username = 5;</code>
     * @param string $var
     * @return $this
     */
    public function setUsername($var)
    {
        GPBUtil::checkString($var, True);
        $this->username = $var;

        return $this;
    }

    /**
     *手机号
     *
     * Generated from protobuf field <code>string mobile = 6;</code>
     * @return string
     */
    public function getMobile()
    {
        return $this->mobile;
    }

    /**
     *手机号
     *
     * Generated from protobuf field <code>string mobile = 6;</code>
     * @param string $var
     * @return $this
     */
    public function setMobile($var)
    {
        GPBUtil::checkString($var, True);
        $this->mobile = $var;

        return $this;
    }

    /**
     *用户头像
     *
     * Generated from protobuf field <code>string head_img = 7;</code>
     * @return string
     */
    public function getHeadImg()
    {
        return $this->head_img;
    }

    /**
     *用户头像
     *
     * Generated from protobuf field <code>string head_img = 7;</code>
     * @param string $var
     * @return $this
     */
    public function setHeadImg($var)
    {
        GPBUtil::checkString($var, True);
        $this->head_img = $var;

        return $this;
    }

    /**
     *用户状态
     *
     * Generated from protobuf field <code>.user.Enumerate status = 8;</code>
     * @return int
     */
    public function getStatus()
    {
        return $this->status;
    }

    /**
     *用户状态
     *
     * Generated from protobuf field <code>.user.Enumerate status = 8;</code>
     * @param int $var
     * @return $this
     */
    public function setStatus($var)
    {
        GPBUtil::checkEnum($var, \User\Enumerate::class);
        $this->status = $var;

        return $this;
    }

    /**
     *自动锁定
     *
     * Generated from protobuf field <code>.user.Enumerate autolock = 9;</code>
     * @return int
     */
    public function getAutolock()
    {
        return $this->autolock;
    }

    /**
     *自动锁定
     *
     * Generated from protobuf field <code>.user.Enumerate autolock = 9;</code>
     * @param int $var
     * @return $this
     */
    public function setAutolock($var)
    {
        GPBUtil::checkEnum($var, \User\Enumerate::class);
        $this->autolock = $var;

        return $this;
    }

    /**
     *是否验证
     *
     * Generated from protobuf field <code>.user.Enumerate verify = 10;</code>
     * @return int
     */
    public function getVerify()
    {
        return $this->verify;
    }

    /**
     *是否验证
     *
     * Generated from protobuf field <code>.user.Enumerate verify = 10;</code>
     * @param int $var
     * @return $this
     */
    public function setVerify($var)
    {
        GPBUtil::checkEnum($var, \User\Enumerate::class);
        $this->verify = $var;

        return $this;
    }

    /**
     *创建时间
     *
     * Generated from protobuf field <code>string create_at = 11;</code>
     * @return string
     */
    public function getCreateAt()
    {
        return $this->create_at;
    }

    /**
     *创建时间
     *
     * Generated from protobuf field <code>string create_at = 11;</code>
     * @param string $var
     * @return $this
     */
    public function setCreateAt($var)
    {
        GPBUtil::checkString($var, True);
        $this->create_at = $var;

        return $this;
    }

    /**
     *更新时间
     *
     * Generated from protobuf field <code>string update_at = 12;</code>
     * @return string
     */
    public function getUpdateAt()
    {
        return $this->update_at;
    }

    /**
     *更新时间
     *
     * Generated from protobuf field <code>string update_at = 12;</code>
     * @param string $var
     * @return $this
     */
    public function setUpdateAt($var)
    {
        GPBUtil::checkString($var, True);
        $this->update_at = $var;

        return $this;
    }

    /**
     *电子邮箱
     *
     * Generated from protobuf field <code>string email = 13;</code>
     * @return string
     */
    public function getEmail()
    {
        return $this->email;
    }

    /**
     *电子邮箱
     *
     * Generated from protobuf field <code>string email = 13;</code>
     * @param string $var
     * @return $this
     */
    public function setEmail($var)
    {
        GPBUtil::checkString($var, True);
        $this->email = $var;

        return $this;
    }

}

