<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: share4.proto

namespace User;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 *用户列表数据
 *
 * Generated from protobuf message <code>user.UserextListsData</code>
 */
class UserextListsData extends \Google\Protobuf\Internal\Message
{
    /**
     *自增id
     *
     * Generated from protobuf field <code>int32 ext_id = 1;</code>
     */
    private $ext_id = 0;
    /**
     *用户id
     *
     * Generated from protobuf field <code>int64 user_id = 2;</code>
     */
    private $user_id = 0;
    /**
     *身份证号码
     *
     * Generated from protobuf field <code>string govid = 3;</code>
     */
    private $govid = '';
    /**
     *身份证文件
     *
     * Generated from protobuf field <code>string govidfile = 4;</code>
     */
    private $govidfile = '';
    /**
     *余额
     *
     * Generated from protobuf field <code>string balance = 5;</code>
     */
    private $balance = '';
    /**
     *审核状态
     *
     * Generated from protobuf field <code>.user.Enumerate check_status = 7;</code>
     */
    private $check_status = 0;
    /**
     *创建时间
     *
     * Generated from protobuf field <code>string create_at = 8;</code>
     */
    private $create_at = '';
    /**
     *更新时间
     *
     * Generated from protobuf field <code>string update_at = 9;</code>
     */
    private $update_at = '';
    /**
     *用户地址
     *
     * Generated from protobuf field <code>string address = 10;</code>
     */
    private $address = '';

    public function __construct() {
        \GPBMetadata\Share4::initOnce();
        parent::__construct();
    }

    /**
     *自增id
     *
     * Generated from protobuf field <code>int32 ext_id = 1;</code>
     * @return int
     */
    public function getExtId()
    {
        return $this->ext_id;
    }

    /**
     *自增id
     *
     * Generated from protobuf field <code>int32 ext_id = 1;</code>
     * @param int $var
     * @return $this
     */
    public function setExtId($var)
    {
        GPBUtil::checkInt32($var);
        $this->ext_id = $var;

        return $this;
    }

    /**
     *用户id
     *
     * Generated from protobuf field <code>int64 user_id = 2;</code>
     * @return int|string
     */
    public function getUserId()
    {
        return $this->user_id;
    }

    /**
     *用户id
     *
     * Generated from protobuf field <code>int64 user_id = 2;</code>
     * @param int|string $var
     * @return $this
     */
    public function setUserId($var)
    {
        GPBUtil::checkInt64($var);
        $this->user_id = $var;

        return $this;
    }

    /**
     *身份证号码
     *
     * Generated from protobuf field <code>string govid = 3;</code>
     * @return string
     */
    public function getGovid()
    {
        return $this->govid;
    }

    /**
     *身份证号码
     *
     * Generated from protobuf field <code>string govid = 3;</code>
     * @param string $var
     * @return $this
     */
    public function setGovid($var)
    {
        GPBUtil::checkString($var, True);
        $this->govid = $var;

        return $this;
    }

    /**
     *身份证文件
     *
     * Generated from protobuf field <code>string govidfile = 4;</code>
     * @return string
     */
    public function getGovidfile()
    {
        return $this->govidfile;
    }

    /**
     *身份证文件
     *
     * Generated from protobuf field <code>string govidfile = 4;</code>
     * @param string $var
     * @return $this
     */
    public function setGovidfile($var)
    {
        GPBUtil::checkString($var, True);
        $this->govidfile = $var;

        return $this;
    }

    /**
     *余额
     *
     * Generated from protobuf field <code>string balance = 5;</code>
     * @return string
     */
    public function getBalance()
    {
        return $this->balance;
    }

    /**
     *余额
     *
     * Generated from protobuf field <code>string balance = 5;</code>
     * @param string $var
     * @return $this
     */
    public function setBalance($var)
    {
        GPBUtil::checkString($var, True);
        $this->balance = $var;

        return $this;
    }

    /**
     *审核状态
     *
     * Generated from protobuf field <code>.user.Enumerate check_status = 7;</code>
     * @return int
     */
    public function getCheckStatus()
    {
        return $this->check_status;
    }

    /**
     *审核状态
     *
     * Generated from protobuf field <code>.user.Enumerate check_status = 7;</code>
     * @param int $var
     * @return $this
     */
    public function setCheckStatus($var)
    {
        GPBUtil::checkEnum($var, \User\Enumerate::class);
        $this->check_status = $var;

        return $this;
    }

    /**
     *创建时间
     *
     * Generated from protobuf field <code>string create_at = 8;</code>
     * @return string
     */
    public function getCreateAt()
    {
        return $this->create_at;
    }

    /**
     *创建时间
     *
     * Generated from protobuf field <code>string create_at = 8;</code>
     * @param string $var
     * @return $this
     */
    public function setCreateAt($var)
    {
        GPBUtil::checkString($var, True);
        $this->create_at = $var;

        return $this;
    }

    /**
     *更新时间
     *
     * Generated from protobuf field <code>string update_at = 9;</code>
     * @return string
     */
    public function getUpdateAt()
    {
        return $this->update_at;
    }

    /**
     *更新时间
     *
     * Generated from protobuf field <code>string update_at = 9;</code>
     * @param string $var
     * @return $this
     */
    public function setUpdateAt($var)
    {
        GPBUtil::checkString($var, True);
        $this->update_at = $var;

        return $this;
    }

    /**
     *用户地址
     *
     * Generated from protobuf field <code>string address = 10;</code>
     * @return string
     */
    public function getAddress()
    {
        return $this->address;
    }

    /**
     *用户地址
     *
     * Generated from protobuf field <code>string address = 10;</code>
     * @param string $var
     * @return $this
     */
    public function setAddress($var)
    {
        GPBUtil::checkString($var, True);
        $this->address = $var;

        return $this;
    }

}

