<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: share4.proto

namespace User;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 *微信用户联查用户表
 *
 * Generated from protobuf message <code>user.WeuserShowUserData</code>
 */
class WeuserShowUserData extends \Google\Protobuf\Internal\Message
{
    /**
     *用户unionid
     *
     * Generated from protobuf field <code>string unionid = 1;</code>
     */
    private $unionid = '';
    /**
     *是否订阅
     *
     * Generated from protobuf field <code>.user.Enumerate subscribe = 2;</code>
     */
    private $subscribe = 0;
    /**
     *用户id
     *
     * Generated from protobuf field <code>int32 user_id = 3;</code>
     */
    private $user_id = 0;
    /**
     *手机号
     *
     * Generated from protobuf field <code>string mobile = 4;</code>
     */
    private $mobile = '';
    /**
     *真实姓名
     *
     * Generated from protobuf field <code>string fullname = 5;</code>
     */
    private $fullname = '';
    /**
     *用户名
     *
     * Generated from protobuf field <code>string username = 6;</code>
     */
    private $username = '';
    /**
     *用户性别
     *
     * Generated from protobuf field <code>.user.Enumerate sex = 7;</code>
     */
    private $sex = 0;

    public function __construct() {
        \GPBMetadata\Share4::initOnce();
        parent::__construct();
    }

    /**
     *用户unionid
     *
     * Generated from protobuf field <code>string unionid = 1;</code>
     * @return string
     */
    public function getUnionid()
    {
        return $this->unionid;
    }

    /**
     *用户unionid
     *
     * Generated from protobuf field <code>string unionid = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setUnionid($var)
    {
        GPBUtil::checkString($var, True);
        $this->unionid = $var;

        return $this;
    }

    /**
     *是否订阅
     *
     * Generated from protobuf field <code>.user.Enumerate subscribe = 2;</code>
     * @return int
     */
    public function getSubscribe()
    {
        return $this->subscribe;
    }

    /**
     *是否订阅
     *
     * Generated from protobuf field <code>.user.Enumerate subscribe = 2;</code>
     * @param int $var
     * @return $this
     */
    public function setSubscribe($var)
    {
        GPBUtil::checkEnum($var, \User\Enumerate::class);
        $this->subscribe = $var;

        return $this;
    }

    /**
     *用户id
     *
     * Generated from protobuf field <code>int32 user_id = 3;</code>
     * @return int
     */
    public function getUserId()
    {
        return $this->user_id;
    }

    /**
     *用户id
     *
     * Generated from protobuf field <code>int32 user_id = 3;</code>
     * @param int $var
     * @return $this
     */
    public function setUserId($var)
    {
        GPBUtil::checkInt32($var);
        $this->user_id = $var;

        return $this;
    }

    /**
     *手机号
     *
     * Generated from protobuf field <code>string mobile = 4;</code>
     * @return string
     */
    public function getMobile()
    {
        return $this->mobile;
    }

    /**
     *手机号
     *
     * Generated from protobuf field <code>string mobile = 4;</code>
     * @param string $var
     * @return $this
     */
    public function setMobile($var)
    {
        GPBUtil::checkString($var, True);
        $this->mobile = $var;

        return $this;
    }

    /**
     *真实姓名
     *
     * Generated from protobuf field <code>string fullname = 5;</code>
     * @return string
     */
    public function getFullname()
    {
        return $this->fullname;
    }

    /**
     *真实姓名
     *
     * Generated from protobuf field <code>string fullname = 5;</code>
     * @param string $var
     * @return $this
     */
    public function setFullname($var)
    {
        GPBUtil::checkString($var, True);
        $this->fullname = $var;

        return $this;
    }

    /**
     *用户名
     *
     * Generated from protobuf field <code>string username = 6;</code>
     * @return string
     */
    public function getUsername()
    {
        return $this->username;
    }

    /**
     *用户名
     *
     * Generated from protobuf field <code>string username = 6;</code>
     * @param string $var
     * @return $this
     */
    public function setUsername($var)
    {
        GPBUtil::checkString($var, True);
        $this->username = $var;

        return $this;
    }

    /**
     *用户性别
     *
     * Generated from protobuf field <code>.user.Enumerate sex = 7;</code>
     * @return int
     */
    public function getSex()
    {
        return $this->sex;
    }

    /**
     *用户性别
     *
     * Generated from protobuf field <code>.user.Enumerate sex = 7;</code>
     * @param int $var
     * @return $this
     */
    public function setSex($var)
    {
        GPBUtil::checkEnum($var, \User\Enumerate::class);
        $this->sex = $var;

        return $this;
    }

}

