<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: address/share4.proto

namespace User\Address;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 *用户地址更新请求体
 *
 * Generated from protobuf message <code>user.address.UseraddressUpdateReq</code>
 */
class UseraddressUpdateReq extends \Google\Protobuf\Internal\Message
{
    /**
     *收货地址id
     *
     * Generated from protobuf field <code>int32 address_id = 1;</code>
     */
    private $address_id = 0;
    /**
     *用户id
     *
     * Generated from protobuf field <code>int32 user_id = 2;</code>
     */
    private $user_id = 0;
    /**
     *收货人地址
     *
     * Generated from protobuf field <code>string receiver_address = 3;</code>
     */
    private $receiver_address = '';
    /**
     *收货人姓名
     *
     * Generated from protobuf field <code>string receiver_name = 4;</code>
     */
    private $receiver_name = '';
    /**
     *收货人手机号
     *
     * Generated from protobuf field <code>string receiver_mobile = 5;</code>
     */
    private $receiver_mobile = '';
    /**
     *收货人区域
     *
     * Generated from protobuf field <code>string receiver_region = 6;</code>
     */
    private $receiver_region = '';

    public function __construct() {
        \GPBMetadata\Address\Share4::initOnce();
        parent::__construct();
    }

    /**
     *收货地址id
     *
     * Generated from protobuf field <code>int32 address_id = 1;</code>
     * @return int
     */
    public function getAddressId()
    {
        return $this->address_id;
    }

    /**
     *收货地址id
     *
     * Generated from protobuf field <code>int32 address_id = 1;</code>
     * @param int $var
     * @return $this
     */
    public function setAddressId($var)
    {
        GPBUtil::checkInt32($var);
        $this->address_id = $var;

        return $this;
    }

    /**
     *用户id
     *
     * Generated from protobuf field <code>int32 user_id = 2;</code>
     * @return int
     */
    public function getUserId()
    {
        return $this->user_id;
    }

    /**
     *用户id
     *
     * Generated from protobuf field <code>int32 user_id = 2;</code>
     * @param int $var
     * @return $this
     */
    public function setUserId($var)
    {
        GPBUtil::checkInt32($var);
        $this->user_id = $var;

        return $this;
    }

    /**
     *收货人地址
     *
     * Generated from protobuf field <code>string receiver_address = 3;</code>
     * @return string
     */
    public function getReceiverAddress()
    {
        return $this->receiver_address;
    }

    /**
     *收货人地址
     *
     * Generated from protobuf field <code>string receiver_address = 3;</code>
     * @param string $var
     * @return $this
     */
    public function setReceiverAddress($var)
    {
        GPBUtil::checkString($var, True);
        $this->receiver_address = $var;

        return $this;
    }

    /**
     *收货人姓名
     *
     * Generated from protobuf field <code>string receiver_name = 4;</code>
     * @return string
     */
    public function getReceiverName()
    {
        return $this->receiver_name;
    }

    /**
     *收货人姓名
     *
     * Generated from protobuf field <code>string receiver_name = 4;</code>
     * @param string $var
     * @return $this
     */
    public function setReceiverName($var)
    {
        GPBUtil::checkString($var, True);
        $this->receiver_name = $var;

        return $this;
    }

    /**
     *收货人手机号
     *
     * Generated from protobuf field <code>string receiver_mobile = 5;</code>
     * @return string
     */
    public function getReceiverMobile()
    {
        return $this->receiver_mobile;
    }

    /**
     *收货人手机号
     *
     * Generated from protobuf field <code>string receiver_mobile = 5;</code>
     * @param string $var
     * @return $this
     */
    public function setReceiverMobile($var)
    {
        GPBUtil::checkString($var, True);
        $this->receiver_mobile = $var;

        return $this;
    }

    /**
     *收货人区域
     *
     * Generated from protobuf field <code>string receiver_region = 6;</code>
     * @return string
     */
    public function getReceiverRegion()
    {
        return $this->receiver_region;
    }

    /**
     *收货人区域
     *
     * Generated from protobuf field <code>string receiver_region = 6;</code>
     * @param string $var
     * @return $this
     */
    public function setReceiverRegion($var)
    {
        GPBUtil::checkString($var, True);
        $this->receiver_region = $var;

        return $this;
    }

}

