<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: member/share4.proto

namespace User\Member;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 *后台用户添加
 *
 * Generated from protobuf message <code>user.member.MemberAddReq</code>
 */
class MemberAddReq extends \Google\Protobuf\Internal\Message
{
    /**
     *是否禁用
     *
     * Generated from protobuf field <code>.user.Enumerate is_lock = 1;</code>
     */
    private $is_lock = 0;
    /**
     *登陆类型
     *
     * Generated from protobuf field <code>.user.Enumerate type = 2;</code>
     */
    private $type = 0;
    /**
     *oa账号
     *
     * Generated from protobuf field <code>string oa = 3;</code>
     */
    private $oa = '';
    /**
     *角色id
     *
     * Generated from protobuf field <code>string role_id = 4;</code>
     */
    private $role_id = '';
    /**
     *性别
     *
     * Generated from protobuf field <code>.user.Enumerate sex = 5;</code>
     */
    private $sex = 0;
    /**
     *手机号
     *
     * Generated from protobuf field <code>string mobile = 6;</code>
     */
    private $mobile = '';
    /**
     *实名信息
     *
     * Generated from protobuf field <code>string fullname = 7;</code>
     */
    private $fullname = '';
    /**
     *用户密码
     *
     * Generated from protobuf field <code>string password = 8;</code>
     */
    private $password = '';
    /**
     *用户名
     *
     * Generated from protobuf field <code>string username = 9;</code>
     */
    private $username = '';
    /**
     *邮箱
     *
     * Generated from protobuf field <code>string email = 10;</code>
     */
    private $email = '';
    /**
     *部门
     *
     * Generated from protobuf field <code>string dept = 13;</code>
     */
    private $dept = '';
    /**
     *账户类别
     *
     * Generated from protobuf field <code>int32 role_type = 14;</code>
     */
    private $role_type = 0;
    /**
     *公司
     *
     * Generated from protobuf field <code>string companies = 15;</code>
     */
    private $companies = '';
    /**
     *是否自动登录
     *
     * Generated from protobuf field <code>.user.Enumerate is_auto_login = 16;</code>
     */
    private $is_auto_login = 0;

    public function __construct() {
        \GPBMetadata\Member\Share4::initOnce();
        parent::__construct();
    }

    /**
     *是否禁用
     *
     * Generated from protobuf field <code>.user.Enumerate is_lock = 1;</code>
     * @return int
     */
    public function getIsLock()
    {
        return $this->is_lock;
    }

    /**
     *是否禁用
     *
     * Generated from protobuf field <code>.user.Enumerate is_lock = 1;</code>
     * @param int $var
     * @return $this
     */
    public function setIsLock($var)
    {
        GPBUtil::checkEnum($var, \User\Enumerate::class);
        $this->is_lock = $var;

        return $this;
    }

    /**
     *登陆类型
     *
     * Generated from protobuf field <code>.user.Enumerate type = 2;</code>
     * @return int
     */
    public function getType()
    {
        return $this->type;
    }

    /**
     *登陆类型
     *
     * Generated from protobuf field <code>.user.Enumerate type = 2;</code>
     * @param int $var
     * @return $this
     */
    public function setType($var)
    {
        GPBUtil::checkEnum($var, \User\Enumerate::class);
        $this->type = $var;

        return $this;
    }

    /**
     *oa账号
     *
     * Generated from protobuf field <code>string oa = 3;</code>
     * @return string
     */
    public function getOa()
    {
        return $this->oa;
    }

    /**
     *oa账号
     *
     * Generated from protobuf field <code>string oa = 3;</code>
     * @param string $var
     * @return $this
     */
    public function setOa($var)
    {
        GPBUtil::checkString($var, True);
        $this->oa = $var;

        return $this;
    }

    /**
     *角色id
     *
     * Generated from protobuf field <code>string role_id = 4;</code>
     * @return string
     */
    public function getRoleId()
    {
        return $this->role_id;
    }

    /**
     *角色id
     *
     * Generated from protobuf field <code>string role_id = 4;</code>
     * @param string $var
     * @return $this
     */
    public function setRoleId($var)
    {
        GPBUtil::checkString($var, True);
        $this->role_id = $var;

        return $this;
    }

    /**
     *性别
     *
     * Generated from protobuf field <code>.user.Enumerate sex = 5;</code>
     * @return int
     */
    public function getSex()
    {
        return $this->sex;
    }

    /**
     *性别
     *
     * Generated from protobuf field <code>.user.Enumerate sex = 5;</code>
     * @param int $var
     * @return $this
     */
    public function setSex($var)
    {
        GPBUtil::checkEnum($var, \User\Enumerate::class);
        $this->sex = $var;

        return $this;
    }

    /**
     *手机号
     *
     * Generated from protobuf field <code>string mobile = 6;</code>
     * @return string
     */
    public function getMobile()
    {
        return $this->mobile;
    }

    /**
     *手机号
     *
     * Generated from protobuf field <code>string mobile = 6;</code>
     * @param string $var
     * @return $this
     */
    public function setMobile($var)
    {
        GPBUtil::checkString($var, True);
        $this->mobile = $var;

        return $this;
    }

    /**
     *实名信息
     *
     * Generated from protobuf field <code>string fullname = 7;</code>
     * @return string
     */
    public function getFullname()
    {
        return $this->fullname;
    }

    /**
     *实名信息
     *
     * Generated from protobuf field <code>string fullname = 7;</code>
     * @param string $var
     * @return $this
     */
    public function setFullname($var)
    {
        GPBUtil::checkString($var, True);
        $this->fullname = $var;

        return $this;
    }

    /**
     *用户密码
     *
     * Generated from protobuf field <code>string password = 8;</code>
     * @return string
     */
    public function getPassword()
    {
        return $this->password;
    }

    /**
     *用户密码
     *
     * Generated from protobuf field <code>string password = 8;</code>
     * @param string $var
     * @return $this
     */
    public function setPassword($var)
    {
        GPBUtil::checkString($var, True);
        $this->password = $var;

        return $this;
    }

    /**
     *用户名
     *
     * Generated from protobuf field <code>string username = 9;</code>
     * @return string
     */
    public function getUsername()
    {
        return $this->username;
    }

    /**
     *用户名
     *
     * Generated from protobuf field <code>string username = 9;</code>
     * @param string $var
     * @return $this
     */
    public function setUsername($var)
    {
        GPBUtil::checkString($var, True);
        $this->username = $var;

        return $this;
    }

    /**
     *邮箱
     *
     * Generated from protobuf field <code>string email = 10;</code>
     * @return string
     */
    public function getEmail()
    {
        return $this->email;
    }

    /**
     *邮箱
     *
     * Generated from protobuf field <code>string email = 10;</code>
     * @param string $var
     * @return $this
     */
    public function setEmail($var)
    {
        GPBUtil::checkString($var, True);
        $this->email = $var;

        return $this;
    }

    /**
     *部门
     *
     * Generated from protobuf field <code>string dept = 13;</code>
     * @return string
     */
    public function getDept()
    {
        return $this->dept;
    }

    /**
     *部门
     *
     * Generated from protobuf field <code>string dept = 13;</code>
     * @param string $var
     * @return $this
     */
    public function setDept($var)
    {
        GPBUtil::checkString($var, True);
        $this->dept = $var;

        return $this;
    }

    /**
     *账户类别
     *
     * Generated from protobuf field <code>int32 role_type = 14;</code>
     * @return int
     */
    public function getRoleType()
    {
        return $this->role_type;
    }

    /**
     *账户类别
     *
     * Generated from protobuf field <code>int32 role_type = 14;</code>
     * @param int $var
     * @return $this
     */
    public function setRoleType($var)
    {
        GPBUtil::checkInt32($var);
        $this->role_type = $var;

        return $this;
    }

    /**
     *公司
     *
     * Generated from protobuf field <code>string companies = 15;</code>
     * @return string
     */
    public function getCompanies()
    {
        return $this->companies;
    }

    /**
     *公司
     *
     * Generated from protobuf field <code>string companies = 15;</code>
     * @param string $var
     * @return $this
     */
    public function setCompanies($var)
    {
        GPBUtil::checkString($var, True);
        $this->companies = $var;

        return $this;
    }

    /**
     *是否自动登录
     *
     * Generated from protobuf field <code>.user.Enumerate is_auto_login = 16;</code>
     * @return int
     */
    public function getIsAutoLogin()
    {
        return $this->is_auto_login;
    }

    /**
     *是否自动登录
     *
     * Generated from protobuf field <code>.user.Enumerate is_auto_login = 16;</code>
     * @param int $var
     * @return $this
     */
    public function setIsAutoLogin($var)
    {
        GPBUtil::checkEnum($var, \User\Enumerate::class);
        $this->is_auto_login = $var;

        return $this;
    }

}

