<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: member/share4.proto

namespace User\Member;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 *后台用户列表
 *
 * Generated from protobuf message <code>user.member.MemberListsReq</code>
 */
class MemberListsReq extends \Google\Protobuf\Internal\Message
{
    /**
     *角色id
     *
     * Generated from protobuf field <code>string role_id = 1;</code>
     */
    private $role_id = '';
    /**
     *角色id
     *
     * Generated from protobuf field <code>string role_ids = 2;</code>
     */
    private $role_ids = '';
    /**
     *oa账号
     *
     * Generated from protobuf field <code>string oa = 3;</code>
     */
    private $oa = '';
    /**
     *用户名
     *
     * Generated from protobuf field <code>string username = 4;</code>
     */
    private $username = '';
    /**
     *停车场id
     *
     * Generated from protobuf field <code>string station = 5;</code>
     */
    private $station = '';
    /**
     *手机号
     *
     * Generated from protobuf field <code>string mobiles = 6;</code>
     */
    private $mobiles = '';
    /**
     *关键字
     *
     * Generated from protobuf field <code>string keyword = 7;</code>
     */
    private $keyword = '';
    /**
     *后台账号id
     *
     * Generated from protobuf field <code>string member_ids = 8;</code>
     */
    private $member_ids = '';
    /**
     *用户实名
     *
     * Generated from protobuf field <code>string fullname = 9;</code>
     */
    private $fullname = '';
    /**
     *登陆类型
     *
     * Generated from protobuf field <code>.user.Enumerate type = 10;</code>
     */
    private $type = 0;
    /**
     *用户id
     *
     * Generated from protobuf field <code>string user_ids = 11;</code>
     */
    private $user_ids = '';
    /**
     *页码
     *
     * Generated from protobuf field <code>int32 page = 12;</code>
     */
    private $page = 0;
    /**
     *页数
     *
     * Generated from protobuf field <code>int32 pagesize = 13;</code>
     */
    private $pagesize = 0;
    /**
     *账户类别
     *
     * Generated from protobuf field <code>int32 role_type = 14;</code>
     */
    private $role_type = 0;
    /**
     *用户id
     *
     * Generated from protobuf field <code>int64 user_id = 15;</code>
     */
    private $user_id = 0;
    /**
     *手机号
     *
     * Generated from protobuf field <code>string mobile = 16;</code>
     */
    private $mobile = '';
    /**
     *后台id
     *
     * Generated from protobuf field <code>int32 member_id = 17;</code>
     */
    private $member_id = 0;
    /**
     *是否锁定
     *
     * Generated from protobuf field <code>.user.Enumerate is_lock = 18;</code>
     */
    private $is_lock = 0;
    /**
     *是否自动登录
     *
     * Generated from protobuf field <code>.user.Enumerate is_auto_login = 19;</code>
     */
    private $is_auto_login = 0;
    /**
     *类型集合
     *
     * Generated from protobuf field <code>repeated int32 role_types = 20;</code>
     */
    private $role_types;

    public function __construct() {
        \GPBMetadata\Member\Share4::initOnce();
        parent::__construct();
    }

    /**
     *角色id
     *
     * Generated from protobuf field <code>string role_id = 1;</code>
     * @return string
     */
    public function getRoleId()
    {
        return $this->role_id;
    }

    /**
     *角色id
     *
     * Generated from protobuf field <code>string role_id = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setRoleId($var)
    {
        GPBUtil::checkString($var, True);
        $this->role_id = $var;

        return $this;
    }

    /**
     *角色id
     *
     * Generated from protobuf field <code>string role_ids = 2;</code>
     * @return string
     */
    public function getRoleIds()
    {
        return $this->role_ids;
    }

    /**
     *角色id
     *
     * Generated from protobuf field <code>string role_ids = 2;</code>
     * @param string $var
     * @return $this
     */
    public function setRoleIds($var)
    {
        GPBUtil::checkString($var, True);
        $this->role_ids = $var;

        return $this;
    }

    /**
     *oa账号
     *
     * Generated from protobuf field <code>string oa = 3;</code>
     * @return string
     */
    public function getOa()
    {
        return $this->oa;
    }

    /**
     *oa账号
     *
     * Generated from protobuf field <code>string oa = 3;</code>
     * @param string $var
     * @return $this
     */
    public function setOa($var)
    {
        GPBUtil::checkString($var, True);
        $this->oa = $var;

        return $this;
    }

    /**
     *用户名
     *
     * Generated from protobuf field <code>string username = 4;</code>
     * @return string
     */
    public function getUsername()
    {
        return $this->username;
    }

    /**
     *用户名
     *
     * Generated from protobuf field <code>string username = 4;</code>
     * @param string $var
     * @return $this
     */
    public function setUsername($var)
    {
        GPBUtil::checkString($var, True);
        $this->username = $var;

        return $this;
    }

    /**
     *停车场id
     *
     * Generated from protobuf field <code>string station = 5;</code>
     * @return string
     */
    public function getStation()
    {
        return $this->station;
    }

    /**
     *停车场id
     *
     * Generated from protobuf field <code>string station = 5;</code>
     * @param string $var
     * @return $this
     */
    public function setStation($var)
    {
        GPBUtil::checkString($var, True);
        $this->station = $var;

        return $this;
    }

    /**
     *手机号
     *
     * Generated from protobuf field <code>string mobiles = 6;</code>
     * @return string
     */
    public function getMobiles()
    {
        return $this->mobiles;
    }

    /**
     *手机号
     *
     * Generated from protobuf field <code>string mobiles = 6;</code>
     * @param string $var
     * @return $this
     */
    public function setMobiles($var)
    {
        GPBUtil::checkString($var, True);
        $this->mobiles = $var;

        return $this;
    }

    /**
     *关键字
     *
     * Generated from protobuf field <code>string keyword = 7;</code>
     * @return string
     */
    public function getKeyword()
    {
        return $this->keyword;
    }

    /**
     *关键字
     *
     * Generated from protobuf field <code>string keyword = 7;</code>
     * @param string $var
     * @return $this
     */
    public function setKeyword($var)
    {
        GPBUtil::checkString($var, True);
        $this->keyword = $var;

        return $this;
    }

    /**
     *后台账号id
     *
     * Generated from protobuf field <code>string member_ids = 8;</code>
     * @return string
     */
    public function getMemberIds()
    {
        return $this->member_ids;
    }

    /**
     *后台账号id
     *
     * Generated from protobuf field <code>string member_ids = 8;</code>
     * @param string $var
     * @return $this
     */
    public function setMemberIds($var)
    {
        GPBUtil::checkString($var, True);
        $this->member_ids = $var;

        return $this;
    }

    /**
     *用户实名
     *
     * Generated from protobuf field <code>string fullname = 9;</code>
     * @return string
     */
    public function getFullname()
    {
        return $this->fullname;
    }

    /**
     *用户实名
     *
     * Generated from protobuf field <code>string fullname = 9;</code>
     * @param string $var
     * @return $this
     */
    public function setFullname($var)
    {
        GPBUtil::checkString($var, True);
        $this->fullname = $var;

        return $this;
    }

    /**
     *登陆类型
     *
     * Generated from protobuf field <code>.user.Enumerate type = 10;</code>
     * @return int
     */
    public function getType()
    {
        return $this->type;
    }

    /**
     *登陆类型
     *
     * Generated from protobuf field <code>.user.Enumerate type = 10;</code>
     * @param int $var
     * @return $this
     */
    public function setType($var)
    {
        GPBUtil::checkEnum($var, \User\Enumerate::class);
        $this->type = $var;

        return $this;
    }

    /**
     *用户id
     *
     * Generated from protobuf field <code>string user_ids = 11;</code>
     * @return string
     */
    public function getUserIds()
    {
        return $this->user_ids;
    }

    /**
     *用户id
     *
     * Generated from protobuf field <code>string user_ids = 11;</code>
     * @param string $var
     * @return $this
     */
    public function setUserIds($var)
    {
        GPBUtil::checkString($var, True);
        $this->user_ids = $var;

        return $this;
    }

    /**
     *页码
     *
     * Generated from protobuf field <code>int32 page = 12;</code>
     * @return int
     */
    public function getPage()
    {
        return $this->page;
    }

    /**
     *页码
     *
     * Generated from protobuf field <code>int32 page = 12;</code>
     * @param int $var
     * @return $this
     */
    public function setPage($var)
    {
        GPBUtil::checkInt32($var);
        $this->page = $var;

        return $this;
    }

    /**
     *页数
     *
     * Generated from protobuf field <code>int32 pagesize = 13;</code>
     * @return int
     */
    public function getPagesize()
    {
        return $this->pagesize;
    }

    /**
     *页数
     *
     * Generated from protobuf field <code>int32 pagesize = 13;</code>
     * @param int $var
     * @return $this
     */
    public function setPagesize($var)
    {
        GPBUtil::checkInt32($var);
        $this->pagesize = $var;

        return $this;
    }

    /**
     *账户类别
     *
     * Generated from protobuf field <code>int32 role_type = 14;</code>
     * @return int
     */
    public function getRoleType()
    {
        return $this->role_type;
    }

    /**
     *账户类别
     *
     * Generated from protobuf field <code>int32 role_type = 14;</code>
     * @param int $var
     * @return $this
     */
    public function setRoleType($var)
    {
        GPBUtil::checkInt32($var);
        $this->role_type = $var;

        return $this;
    }

    /**
     *用户id
     *
     * Generated from protobuf field <code>int64 user_id = 15;</code>
     * @return int|string
     */
    public function getUserId()
    {
        return $this->user_id;
    }

    /**
     *用户id
     *
     * Generated from protobuf field <code>int64 user_id = 15;</code>
     * @param int|string $var
     * @return $this
     */
    public function setUserId($var)
    {
        GPBUtil::checkInt64($var);
        $this->user_id = $var;

        return $this;
    }

    /**
     *手机号
     *
     * Generated from protobuf field <code>string mobile = 16;</code>
     * @return string
     */
    public function getMobile()
    {
        return $this->mobile;
    }

    /**
     *手机号
     *
     * Generated from protobuf field <code>string mobile = 16;</code>
     * @param string $var
     * @return $this
     */
    public function setMobile($var)
    {
        GPBUtil::checkString($var, True);
        $this->mobile = $var;

        return $this;
    }

    /**
     *后台id
     *
     * Generated from protobuf field <code>int32 member_id = 17;</code>
     * @return int
     */
    public function getMemberId()
    {
        return $this->member_id;
    }

    /**
     *后台id
     *
     * Generated from protobuf field <code>int32 member_id = 17;</code>
     * @param int $var
     * @return $this
     */
    public function setMemberId($var)
    {
        GPBUtil::checkInt32($var);
        $this->member_id = $var;

        return $this;
    }

    /**
     *是否锁定
     *
     * Generated from protobuf field <code>.user.Enumerate is_lock = 18;</code>
     * @return int
     */
    public function getIsLock()
    {
        return $this->is_lock;
    }

    /**
     *是否锁定
     *
     * Generated from protobuf field <code>.user.Enumerate is_lock = 18;</code>
     * @param int $var
     * @return $this
     */
    public function setIsLock($var)
    {
        GPBUtil::checkEnum($var, \User\Enumerate::class);
        $this->is_lock = $var;

        return $this;
    }

    /**
     *是否自动登录
     *
     * Generated from protobuf field <code>.user.Enumerate is_auto_login = 19;</code>
     * @return int
     */
    public function getIsAutoLogin()
    {
        return $this->is_auto_login;
    }

    /**
     *是否自动登录
     *
     * Generated from protobuf field <code>.user.Enumerate is_auto_login = 19;</code>
     * @param int $var
     * @return $this
     */
    public function setIsAutoLogin($var)
    {
        GPBUtil::checkEnum($var, \User\Enumerate::class);
        $this->is_auto_login = $var;

        return $this;
    }

    /**
     *类型集合
     *
     * Generated from protobuf field <code>repeated int32 role_types = 20;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getRoleTypes()
    {
        return $this->role_types;
    }

    /**
     *类型集合
     *
     * Generated from protobuf field <code>repeated int32 role_types = 20;</code>
     * @param int[]|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setRoleTypes($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::INT32);
        $this->role_types = $arr;

        return $this;
    }

}

