<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: member/share4.proto

namespace User\Member;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 *后台用户列表计数
 *
 * Generated from protobuf message <code>user.member.MemberCountReq</code>
 */
class MemberCountReq extends \Google\Protobuf\Internal\Message
{
    /**
     *用户id
     *
     * Generated from protobuf field <code>string role_id = 1;</code>
     */
    private $role_id = '';
    /**
     *用户id
     *
     * Generated from protobuf field <code>string role_ids = 2;</code>
     */
    private $role_ids = '';
    /**
     *oa账号
     *
     * Generated from protobuf field <code>string oa = 3;</code>
     */
    private $oa = '';
    /**
     *用户账号
     *
     * Generated from protobuf field <code>string username = 4;</code>
     */
    private $username = '';
    /**
     *停车场
     *
     * Generated from protobuf field <code>string station = 5;</code>
     */
    private $station = '';
    /**
     *手机号
     *
     * Generated from protobuf field <code>string mobiles = 6;</code>
     */
    private $mobiles = '';
    /**
     *关键字
     *
     * Generated from protobuf field <code>string keyword = 7;</code>
     */
    private $keyword = '';
    /**
     *后台账户id
     *
     * Generated from protobuf field <code>string member_ids = 8;</code>
     */
    private $member_ids = '';
    /**
     *实名
     *
     * Generated from protobuf field <code>string fullname = 9;</code>
     */
    private $fullname = '';
    /**
     *账户类别
     *
     * Generated from protobuf field <code>int32 role_type = 10;</code>
     */
    private $role_type = 0;
    /**
     *是否自动登录
     *
     * Generated from protobuf field <code>.user.Enumerate is_auto_login = 11;</code>
     */
    private $is_auto_login = 0;
    /**
     *类型集合
     *
     * Generated from protobuf field <code>repeated int32 role_types = 12;</code>
     */
    private $role_types;

    public function __construct() {
        \GPBMetadata\Member\Share4::initOnce();
        parent::__construct();
    }

    /**
     *用户id
     *
     * Generated from protobuf field <code>string role_id = 1;</code>
     * @return string
     */
    public function getRoleId()
    {
        return $this->role_id;
    }

    /**
     *用户id
     *
     * Generated from protobuf field <code>string role_id = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setRoleId($var)
    {
        GPBUtil::checkString($var, True);
        $this->role_id = $var;

        return $this;
    }

    /**
     *用户id
     *
     * Generated from protobuf field <code>string role_ids = 2;</code>
     * @return string
     */
    public function getRoleIds()
    {
        return $this->role_ids;
    }

    /**
     *用户id
     *
     * Generated from protobuf field <code>string role_ids = 2;</code>
     * @param string $var
     * @return $this
     */
    public function setRoleIds($var)
    {
        GPBUtil::checkString($var, True);
        $this->role_ids = $var;

        return $this;
    }

    /**
     *oa账号
     *
     * Generated from protobuf field <code>string oa = 3;</code>
     * @return string
     */
    public function getOa()
    {
        return $this->oa;
    }

    /**
     *oa账号
     *
     * Generated from protobuf field <code>string oa = 3;</code>
     * @param string $var
     * @return $this
     */
    public function setOa($var)
    {
        GPBUtil::checkString($var, True);
        $this->oa = $var;

        return $this;
    }

    /**
     *用户账号
     *
     * Generated from protobuf field <code>string username = 4;</code>
     * @return string
     */
    public function getUsername()
    {
        return $this->username;
    }

    /**
     *用户账号
     *
     * Generated from protobuf field <code>string username = 4;</code>
     * @param string $var
     * @return $this
     */
    public function setUsername($var)
    {
        GPBUtil::checkString($var, True);
        $this->username = $var;

        return $this;
    }

    /**
     *停车场
     *
     * Generated from protobuf field <code>string station = 5;</code>
     * @return string
     */
    public function getStation()
    {
        return $this->station;
    }

    /**
     *停车场
     *
     * Generated from protobuf field <code>string station = 5;</code>
     * @param string $var
     * @return $this
     */
    public function setStation($var)
    {
        GPBUtil::checkString($var, True);
        $this->station = $var;

        return $this;
    }

    /**
     *手机号
     *
     * Generated from protobuf field <code>string mobiles = 6;</code>
     * @return string
     */
    public function getMobiles()
    {
        return $this->mobiles;
    }

    /**
     *手机号
     *
     * Generated from protobuf field <code>string mobiles = 6;</code>
     * @param string $var
     * @return $this
     */
    public function setMobiles($var)
    {
        GPBUtil::checkString($var, True);
        $this->mobiles = $var;

        return $this;
    }

    /**
     *关键字
     *
     * Generated from protobuf field <code>string keyword = 7;</code>
     * @return string
     */
    public function getKeyword()
    {
        return $this->keyword;
    }

    /**
     *关键字
     *
     * Generated from protobuf field <code>string keyword = 7;</code>
     * @param string $var
     * @return $this
     */
    public function setKeyword($var)
    {
        GPBUtil::checkString($var, True);
        $this->keyword = $var;

        return $this;
    }

    /**
     *后台账户id
     *
     * Generated from protobuf field <code>string member_ids = 8;</code>
     * @return string
     */
    public function getMemberIds()
    {
        return $this->member_ids;
    }

    /**
     *后台账户id
     *
     * Generated from protobuf field <code>string member_ids = 8;</code>
     * @param string $var
     * @return $this
     */
    public function setMemberIds($var)
    {
        GPBUtil::checkString($var, True);
        $this->member_ids = $var;

        return $this;
    }

    /**
     *实名
     *
     * Generated from protobuf field <code>string fullname = 9;</code>
     * @return string
     */
    public function getFullname()
    {
        return $this->fullname;
    }

    /**
     *实名
     *
     * Generated from protobuf field <code>string fullname = 9;</code>
     * @param string $var
     * @return $this
     */
    public function setFullname($var)
    {
        GPBUtil::checkString($var, True);
        $this->fullname = $var;

        return $this;
    }

    /**
     *账户类别
     *
     * Generated from protobuf field <code>int32 role_type = 10;</code>
     * @return int
     */
    public function getRoleType()
    {
        return $this->role_type;
    }

    /**
     *账户类别
     *
     * Generated from protobuf field <code>int32 role_type = 10;</code>
     * @param int $var
     * @return $this
     */
    public function setRoleType($var)
    {
        GPBUtil::checkInt32($var);
        $this->role_type = $var;

        return $this;
    }

    /**
     *是否自动登录
     *
     * Generated from protobuf field <code>.user.Enumerate is_auto_login = 11;</code>
     * @return int
     */
    public function getIsAutoLogin()
    {
        return $this->is_auto_login;
    }

    /**
     *是否自动登录
     *
     * Generated from protobuf field <code>.user.Enumerate is_auto_login = 11;</code>
     * @param int $var
     * @return $this
     */
    public function setIsAutoLogin($var)
    {
        GPBUtil::checkEnum($var, \User\Enumerate::class);
        $this->is_auto_login = $var;

        return $this;
    }

    /**
     *类型集合
     *
     * Generated from protobuf field <code>repeated int32 role_types = 12;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getRoleTypes()
    {
        return $this->role_types;
    }

    /**
     *类型集合
     *
     * Generated from protobuf field <code>repeated int32 role_types = 12;</code>
     * @param int[]|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setRoleTypes($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::INT32);
        $this->role_types = $arr;

        return $this;
    }

}

