<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: userext/share4.proto

namespace User\Userext;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 *用户拓展信息请求体
 *
 * Generated from protobuf message <code>user.userext.UserextShowReq</code>
 */
class UserextShowReq extends \Google\Protobuf\Internal\Message
{
    /**
     *用户id
     *
     * Generated from protobuf field <code>int64 user_id = 1;</code>
     */
    private $user_id = 0;
    /**
     *拓展id
     *
     * Generated from protobuf field <code>int32 ext_id = 2;</code>
     */
    private $ext_id = 0;

    public function __construct() {
        \GPBMetadata\Userext\Share4::initOnce();
        parent::__construct();
    }

    /**
     *用户id
     *
     * Generated from protobuf field <code>int64 user_id = 1;</code>
     * @return int|string
     */
    public function getUserId()
    {
        return $this->user_id;
    }

    /**
     *用户id
     *
     * Generated from protobuf field <code>int64 user_id = 1;</code>
     * @param int|string $var
     * @return $this
     */
    public function setUserId($var)
    {
        GPBUtil::checkInt64($var);
        $this->user_id = $var;

        return $this;
    }

    /**
     *拓展id
     *
     * Generated from protobuf field <code>int32 ext_id = 2;</code>
     * @return int
     */
    public function getExtId()
    {
        return $this->ext_id;
    }

    /**
     *拓展id
     *
     * Generated from protobuf field <code>int32 ext_id = 2;</code>
     * @param int $var
     * @return $this
     */
    public function setExtId($var)
    {
        GPBUtil::checkInt32($var);
        $this->ext_id = $var;

        return $this;
    }

}

