<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: userext/share4.proto

namespace User\Userext;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 *用户列表请求体
 *
 * Generated from protobuf message <code>user.userext.UserextListsReq</code>
 */
class UserextListsReq extends \Google\Protobuf\Internal\Message
{
    /**
     *页数
     *
     * Generated from protobuf field <code>int32 page = 1;</code>
     */
    private $page = 0;
    /**
     *页码
     *
     * Generated from protobuf field <code>int32 pagesize = 2;</code>
     */
    private $pagesize = 0;
    /**
     *用户id
     *
     * Generated from protobuf field <code>int64 user_id = 5;</code>
     */
    private $user_id = 0;
    /**
     *拓展id
     *
     * Generated from protobuf field <code>string ext_id = 6;</code>
     */
    private $ext_id = '';

    public function __construct() {
        \GPBMetadata\Userext\Share4::initOnce();
        parent::__construct();
    }

    /**
     *页数
     *
     * Generated from protobuf field <code>int32 page = 1;</code>
     * @return int
     */
    public function getPage()
    {
        return $this->page;
    }

    /**
     *页数
     *
     * Generated from protobuf field <code>int32 page = 1;</code>
     * @param int $var
     * @return $this
     */
    public function setPage($var)
    {
        GPBUtil::checkInt32($var);
        $this->page = $var;

        return $this;
    }

    /**
     *页码
     *
     * Generated from protobuf field <code>int32 pagesize = 2;</code>
     * @return int
     */
    public function getPagesize()
    {
        return $this->pagesize;
    }

    /**
     *页码
     *
     * Generated from protobuf field <code>int32 pagesize = 2;</code>
     * @param int $var
     * @return $this
     */
    public function setPagesize($var)
    {
        GPBUtil::checkInt32($var);
        $this->pagesize = $var;

        return $this;
    }

    /**
     *用户id
     *
     * Generated from protobuf field <code>int64 user_id = 5;</code>
     * @return int|string
     */
    public function getUserId()
    {
        return $this->user_id;
    }

    /**
     *用户id
     *
     * Generated from protobuf field <code>int64 user_id = 5;</code>
     * @param int|string $var
     * @return $this
     */
    public function setUserId($var)
    {
        GPBUtil::checkInt64($var);
        $this->user_id = $var;

        return $this;
    }

    /**
     *拓展id
     *
     * Generated from protobuf field <code>string ext_id = 6;</code>
     * @return string
     */
    public function getExtId()
    {
        return $this->ext_id;
    }

    /**
     *拓展id
     *
     * Generated from protobuf field <code>string ext_id = 6;</code>
     * @param string $var
     * @return $this
     */
    public function setExtId($var)
    {
        GPBUtil::checkString($var, True);
        $this->ext_id = $var;

        return $this;
    }

}

