<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: userjsz/share4.proto

namespace User\Userjsz;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 *驾驶证计数请求体
 *
 * Generated from protobuf message <code>user.userjsz.JszCountReq</code>
 */
class JszCountReq extends \Google\Protobuf\Internal\Message
{
    /**
     *驾驶证id
     *
     * Generated from protobuf field <code>int32 jsz_id = 1;</code>
     */
    private $jsz_id = 0;
    /**
     *驾驶证号码
     *
     * Generated from protobuf field <code>string jsz_number = 2;</code>
     */
    private $jsz_number = '';
    /**
     *用户id
     *
     * Generated from protobuf field <code>int64 user_id = 3;</code>
     */
    private $user_id = 0;
    /**
     *实名
     *
     * Generated from protobuf field <code>string real_name = 4;</code>
     */
    private $real_name = '';
    /**
     *驾驶类型
     *
     * Generated from protobuf field <code>string drive_type = 5;</code>
     */
    private $drive_type = '';
    /**
     *性别
     *
     * Generated from protobuf field <code>.user.Enumerate sex = 6;</code>
     */
    private $sex = 0;
    /**
     *国籍
     *
     * Generated from protobuf field <code>string national = 7;</code>
     */
    private $national = '';

    public function __construct() {
        \GPBMetadata\Userjsz\Share4::initOnce();
        parent::__construct();
    }

    /**
     *驾驶证id
     *
     * Generated from protobuf field <code>int32 jsz_id = 1;</code>
     * @return int
     */
    public function getJszId()
    {
        return $this->jsz_id;
    }

    /**
     *驾驶证id
     *
     * Generated from protobuf field <code>int32 jsz_id = 1;</code>
     * @param int $var
     * @return $this
     */
    public function setJszId($var)
    {
        GPBUtil::checkInt32($var);
        $this->jsz_id = $var;

        return $this;
    }

    /**
     *驾驶证号码
     *
     * Generated from protobuf field <code>string jsz_number = 2;</code>
     * @return string
     */
    public function getJszNumber()
    {
        return $this->jsz_number;
    }

    /**
     *驾驶证号码
     *
     * Generated from protobuf field <code>string jsz_number = 2;</code>
     * @param string $var
     * @return $this
     */
    public function setJszNumber($var)
    {
        GPBUtil::checkString($var, True);
        $this->jsz_number = $var;

        return $this;
    }

    /**
     *用户id
     *
     * Generated from protobuf field <code>int64 user_id = 3;</code>
     * @return int|string
     */
    public function getUserId()
    {
        return $this->user_id;
    }

    /**
     *用户id
     *
     * Generated from protobuf field <code>int64 user_id = 3;</code>
     * @param int|string $var
     * @return $this
     */
    public function setUserId($var)
    {
        GPBUtil::checkInt64($var);
        $this->user_id = $var;

        return $this;
    }

    /**
     *实名
     *
     * Generated from protobuf field <code>string real_name = 4;</code>
     * @return string
     */
    public function getRealName()
    {
        return $this->real_name;
    }

    /**
     *实名
     *
     * Generated from protobuf field <code>string real_name = 4;</code>
     * @param string $var
     * @return $this
     */
    public function setRealName($var)
    {
        GPBUtil::checkString($var, True);
        $this->real_name = $var;

        return $this;
    }

    /**
     *驾驶类型
     *
     * Generated from protobuf field <code>string drive_type = 5;</code>
     * @return string
     */
    public function getDriveType()
    {
        return $this->drive_type;
    }

    /**
     *驾驶类型
     *
     * Generated from protobuf field <code>string drive_type = 5;</code>
     * @param string $var
     * @return $this
     */
    public function setDriveType($var)
    {
        GPBUtil::checkString($var, True);
        $this->drive_type = $var;

        return $this;
    }

    /**
     *性别
     *
     * Generated from protobuf field <code>.user.Enumerate sex = 6;</code>
     * @return int
     */
    public function getSex()
    {
        return $this->sex;
    }

    /**
     *性别
     *
     * Generated from protobuf field <code>.user.Enumerate sex = 6;</code>
     * @param int $var
     * @return $this
     */
    public function setSex($var)
    {
        GPBUtil::checkEnum($var, \User\Enumerate::class);
        $this->sex = $var;

        return $this;
    }

    /**
     *国籍
     *
     * Generated from protobuf field <code>string national = 7;</code>
     * @return string
     */
    public function getNational()
    {
        return $this->national;
    }

    /**
     *国籍
     *
     * Generated from protobuf field <code>string national = 7;</code>
     * @param string $var
     * @return $this
     */
    public function setNational($var)
    {
        GPBUtil::checkString($var, True);
        $this->national = $var;

        return $this;
    }

}

