<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: authmidware/share4.proto

namespace GPBMetadata\Authmidware;

class Share4
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        \GPBMetadata\Share4::initOnce();
        $pool->internalAddGeneratedFile(hex2bin(
            "0aff010a18617574686d6964776172652f7368617265342e70726f746f12" .
            "10757365722e617574686d69647761726522410a16417069617574685365" .
            "7475736572726f75746552657112140a0c6163636573735f746f6b656e18" .
            "012001280912110a09726f7574655f69647318022001280922490a174170" .
            "6961757468536574726f7574656361636865526571122e0a06726f757465" .
            "7318012003280b321e2e757365722e41706961757468536574726f757465" .
            "636163686544617461223b0a184170706175746847657441636365737354" .
            "6f6b656e52657112110a0965745f6170705f6964180120012809120c0a04" .
            "7369676e180220012809620670726f746f33"
        ));

        static::$is_initialized = true;
    }
}

